package space.alnovis.protowrapper.generator.wellknown;

import com.squareup.javapoet.*;

import javax.lang.model.element.Modifier;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Generates the StructConverter utility class for converting between
 * protobuf Struct/Value/ListValue and Java Map/Object/List.
 *
 * <p>The generated class provides static methods for bidirectional conversion:</p>
 * <ul>
 *   <li>{@code toMap(Struct)} - converts Struct to Map&lt;String, Object&gt;</li>
 *   <li>{@code toStruct(Map)} - converts Map&lt;String, Object&gt; to Struct</li>
 *   <li>{@code toObject(Value)} - converts Value to Object</li>
 *   <li>{@code toValue(Object)} - converts Object to Value</li>
 *   <li>{@code toList(ListValue)} - converts ListValue to List&lt;Object&gt;</li>
 *   <li>{@code toListValue(List)} - converts List&lt;Object&gt; to ListValue</li>
 * </ul>
 *
 * @since 1.3.0
 */
public final class StructConverterGenerator {

    private static final ClassName STRUCT = ClassName.get("com.google.protobuf", "Struct");
    private static final ClassName VALUE = ClassName.get("com.google.protobuf", "Value");
    private static final ClassName LIST_VALUE = ClassName.get("com.google.protobuf", "ListValue");
    private static final ClassName NULL_VALUE = ClassName.get("com.google.protobuf", "NullValue");

    private StructConverterGenerator() {
    }

    /**
     * Generate the StructConverter utility class.
     *
     * @param packageName Target package for the generated class
     * @return JavaFile containing the StructConverter class
     */
    public static JavaFile generate(String packageName) {
        TypeSpec structConverter = TypeSpec.classBuilder("StructConverter")
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addJavadoc("Utility class for converting between protobuf Struct/Value/ListValue and Java types.\n")
                .addJavadoc("\n<p>Generated by proto-wrapper-plugin.</p>\n")
                .addMethod(privateConstructor())
                .addMethod(toMapMethod())
                .addMethod(toStructMethod())
                .addMethod(toObjectMethod())
                .addMethod(toValueMethod())
                .addMethod(toListMethod())
                .addMethod(toListValueMethod())
                .build();

        return JavaFile.builder(packageName, structConverter)
                .addFileComment("Generated by proto-wrapper-plugin. Do not edit.")
                .skipJavaLangImports(true)
                .build();
    }

    private static MethodSpec privateConstructor() {
        return MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PRIVATE)
                .build();
    }

    /**
     * Struct -> Map<String, Object>
     */
    private static MethodSpec toMapMethod() {
        ParameterizedTypeName returnType = ParameterizedTypeName.get(
                ClassName.get(Map.class),
                ClassName.get(String.class),
                ClassName.get(Object.class)
        );

        return MethodSpec.methodBuilder("toMap")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addJavadoc("Convert protobuf Struct to Java Map.\n")
                .addJavadoc("\n@param struct the protobuf Struct\n")
                .addJavadoc("@return Map representation of the Struct\n")
                .addParameter(STRUCT, "struct")
                .returns(returnType)
                .beginControlFlow("if (struct == null)")
                .addStatement("return $T.emptyMap()", java.util.Collections.class)
                .endControlFlow()
                .addStatement("return struct.getFieldsMap().entrySet().stream()\n" +
                        "        .collect($T.toMap($T.Entry::getKey, e -> toObject(e.getValue())))",
                        Collectors.class, Map.class)
                .build();
    }

    /**
     * Map<String, Object> -> Struct
     */
    private static MethodSpec toStructMethod() {
        ParameterizedTypeName paramType = ParameterizedTypeName.get(
                ClassName.get(Map.class),
                ClassName.get(String.class),
                WildcardTypeName.subtypeOf(Object.class)
        );

        return MethodSpec.methodBuilder("toStruct")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addJavadoc("Convert Java Map to protobuf Struct.\n")
                .addJavadoc("\n@param map the Java Map\n")
                .addJavadoc("@return Struct representation of the Map\n")
                .addParameter(paramType, "map")
                .returns(STRUCT)
                .beginControlFlow("if (map == null || map.isEmpty())")
                .addStatement("return $T.getDefaultInstance()", STRUCT)
                .endControlFlow()
                .addStatement("$T.Builder builder = $T.newBuilder()", STRUCT, STRUCT)
                .beginControlFlow("for ($T.Entry<String, ?> entry : map.entrySet())", Map.class)
                .addStatement("builder.putFields(entry.getKey(), toValue(entry.getValue()))")
                .endControlFlow()
                .addStatement("return builder.build()")
                .build();
    }

    /**
     * Value -> Object
     */
    private static MethodSpec toObjectMethod() {
        return MethodSpec.methodBuilder("toObject")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addJavadoc("Convert protobuf Value to Java Object.\n")
                .addJavadoc("\n@param value the protobuf Value\n")
                .addJavadoc("@return Java Object representation (null, Double, String, Boolean, Map, or List)\n")
                .addParameter(VALUE, "value")
                .returns(Object.class)
                .beginControlFlow("if (value == null)")
                .addStatement("return null")
                .endControlFlow()
                .beginControlFlow("return switch (value.getKindCase())")
                .addStatement("case NULL_VALUE -> null")
                .addStatement("case NUMBER_VALUE -> value.getNumberValue()")
                .addStatement("case STRING_VALUE -> value.getStringValue()")
                .addStatement("case BOOL_VALUE -> value.getBoolValue()")
                .addStatement("case STRUCT_VALUE -> toMap(value.getStructValue())")
                .addStatement("case LIST_VALUE -> toList(value.getListValue())")
                .addStatement("case KIND_NOT_SET -> null")
                .endControlFlow("")
                .build();
    }

    /**
     * Object -> Value
     */
    private static MethodSpec toValueMethod() {
        return MethodSpec.methodBuilder("toValue")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addJavadoc("Convert Java Object to protobuf Value.\n")
                .addJavadoc("\n@param obj the Java Object (null, Number, String, Boolean, Map, or List)\n")
                .addJavadoc("@return Value representation of the Object\n")
                .addParameter(Object.class, "obj")
                .returns(VALUE)
                .beginControlFlow("if (obj == null)")
                .addStatement("return $T.newBuilder().setNullValue($T.NULL_VALUE).build()", VALUE, NULL_VALUE)
                .endControlFlow()
                .beginControlFlow("if (obj instanceof Number n)")
                .addStatement("return $T.newBuilder().setNumberValue(n.doubleValue()).build()", VALUE)
                .endControlFlow()
                .beginControlFlow("if (obj instanceof String s)")
                .addStatement("return $T.newBuilder().setStringValue(s).build()", VALUE)
                .endControlFlow()
                .beginControlFlow("if (obj instanceof Boolean b)")
                .addStatement("return $T.newBuilder().setBoolValue(b).build()", VALUE)
                .endControlFlow()
                .beginControlFlow("if (obj instanceof $T<?, ?> map)", Map.class)
                .addStatement("@SuppressWarnings(\"unchecked\")\n" +
                        "$T<String, ?> stringMap = ($T<String, ?>) map", Map.class, Map.class)
                .addStatement("return $T.newBuilder().setStructValue(toStruct(stringMap)).build()", VALUE)
                .endControlFlow()
                .beginControlFlow("if (obj instanceof $T<?> list)", List.class)
                .addStatement("return $T.newBuilder().setListValue(toListValue(list)).build()", VALUE)
                .endControlFlow()
                .addComment("Fallback: convert to string")
                .addStatement("return $T.newBuilder().setStringValue(obj.toString()).build()", VALUE)
                .build();
    }

    /**
     * ListValue -> List<Object>
     */
    private static MethodSpec toListMethod() {
        ParameterizedTypeName returnType = ParameterizedTypeName.get(
                ClassName.get(List.class),
                ClassName.get(Object.class)
        );

        return MethodSpec.methodBuilder("toList")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addJavadoc("Convert protobuf ListValue to Java List.\n")
                .addJavadoc("\n@param listValue the protobuf ListValue\n")
                .addJavadoc("@return List representation of the ListValue\n")
                .addParameter(LIST_VALUE, "listValue")
                .returns(returnType)
                .beginControlFlow("if (listValue == null)")
                .addStatement("return $T.emptyList()", java.util.Collections.class)
                .endControlFlow()
                .addStatement("return listValue.getValuesList().stream()\n" +
                        "        .map(StructConverter::toObject)\n" +
                        "        .collect($T.toList())", Collectors.class)
                .build();
    }

    /**
     * List<Object> -> ListValue
     */
    private static MethodSpec toListValueMethod() {
        ParameterizedTypeName paramType = ParameterizedTypeName.get(
                ClassName.get(List.class),
                WildcardTypeName.subtypeOf(Object.class)
        );

        return MethodSpec.methodBuilder("toListValue")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addJavadoc("Convert Java List to protobuf ListValue.\n")
                .addJavadoc("\n@param list the Java List\n")
                .addJavadoc("@return ListValue representation of the List\n")
                .addParameter(paramType, "list")
                .returns(LIST_VALUE)
                .beginControlFlow("if (list == null || list.isEmpty())")
                .addStatement("return $T.getDefaultInstance()", LIST_VALUE)
                .endControlFlow()
                .addStatement("$T.Builder builder = $T.newBuilder()", LIST_VALUE, LIST_VALUE)
                .beginControlFlow("for (Object item : list)")
                .addStatement("builder.addValues(toValue(item))")
                .endControlFlow()
                .addStatement("return builder.build()")
                .build();
    }
}
