// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto2.wrapper.api;

import com.google.protobuf.Message;
import java.lang.String;

/**
 * Common interface for all generated wrapper classes.
 *
 * <p>This interface provides a unified way to access the underlying protobuf message
 * and common wrapper methods without reflection.</p>
 *
 * <p>All generated wrapper interfaces extend this interface, enabling type-safe
 * access to wrapped protos:</p>
 * <pre>{@code
 * if (wrapper instanceof ProtoWrapper pw) {
 *     Message proto = pw.getTypedProto();
 *     String versionId = pw.getWrapperVersionId();
 * }
 * }</pre>
 *
 * @since 1.6.6
 */
public interface ProtoWrapper {
    /**
     * Get the underlying protobuf message.
     *
     * <p>The returned message is the actual protobuf object wrapped by this instance.
     * The concrete type depends on the protocol version (e.g., v1.Order or v2.Order).</p>
     *
     * @return underlying protobuf Message, never null
     */
    Message getTypedProto();

    /**
     * Get the version identifier this wrapper was created from.
     *
     * @return version identifier (e.g., "v1", "v2")
     */
    String getWrapperVersionId();

    /**
     * Serialize to protobuf bytes.
     *
     * @return protobuf-encoded bytes
     */
    byte[] toBytes();
}
