// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto2.wrapper.api;

import java.lang.IllegalArgumentException;
import java.lang.Object;
import java.lang.ReflectiveOperationException;
import java.lang.reflect.Method;

/**
 * Version-agnostic enum for TestEnum.
 *
 * <p>Supported in versions: [v1, v2]</p>
 */
public enum TestEnum {
    UNKNOWN(0),

    ONE(1),

    TWO(2),

    THREE(3);

    private final int value;

    TestEnum(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    /**
     * Convert proto enum numeric value to this enum.
     * @param value Proto enum ordinal
     * @return Matching enum constant or null if not found
     */
    public static TestEnum fromProtoValue(int value) {
        for (TestEnum e : values()) {
            if (e.value == value) {
                return e;
            }
        }
        return null;
    }

    /**
     * Convert any proto enum to this wrapper enum.
     *
     * <p>Works with any version's proto enum by extracting numeric value via reflection.</p>
     *
     * @param protoEnum Proto enum instance (e.g., v202.Message.CommandTypeEnum.COMMAND_INFO)
     * @return Corresponding wrapper enum constant, or null if value not found
     * @throws IllegalArgumentException if protoEnum is not a valid protobuf enum
     */
    public static TestEnum fromProto(Object protoEnum) {
        if (protoEnum == null) {
            return null;
        }
        try {
            Method getNumber = protoEnum.getClass().getMethod("getNumber");
            int number = (int) getNumber.invoke(protoEnum);
            return fromProtoValue(number);
        } catch (ReflectiveOperationException e) {
            throw new IllegalArgumentException("Cannot convert to TestEnum: " + protoEnum.getClass().getName(), e);
        }
    }

    /**
     * Check if this wrapper enum matches a proto enum by numeric value.
     *
     * <p>Works with any version's proto enum.</p>
     *
     * @param protoEnum Proto enum to compare with
     * @return true if numeric values match, false otherwise
     */
    public boolean matches(Object protoEnum) {
        if (protoEnum == null) {
            return false;
        }
        try {
            Method getNumber = protoEnum.getClass().getMethod("getNumber");
            int number = (int) getNumber.invoke(protoEnum);
            return this.value == number;
        } catch (ReflectiveOperationException e) {
            return false;
        }
    }
}
