package space.alnovis.protowrapper.generator;

import com.squareup.javapoet.ClassName;

/**
 * Constants for protobuf-related code generation.
 *
 * <p>Centralizes magic strings and commonly used class names to avoid
 * duplication and improve maintainability. All constants are organized
 * into logical groups.</p>
 *
 * <h2>Constant Groups</h2>
 * <ul>
 *   <li><b>Package names:</b> Protobuf library package</li>
 *   <li><b>Class names:</b> JavaPoet ClassName for common protobuf types</li>
 *   <li><b>Package suffixes:</b> Conventions for generated package structure</li>
 *   <li><b>Placeholders:</b> Template placeholders for pattern replacement</li>
 *   <li><b>Method prefixes:</b> Standard prefixes for generated method names</li>
 * </ul>
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * // Use class names in JavaPoet generation
 * MethodSpec.methodBuilder("toBytes")
 *     .returns(ProtobufConstants.BYTE_STRING_CLASS)
 *     .build();
 *
 * // Use method prefixes for consistent naming
 * String methodName = ProtobufConstants.EXTRACT_PREFIX + capitalize(fieldName);
 * }</pre>
 *
 * @see GeneratorConfig
 * @see TypeResolver
 */
public final class ProtobufConstants {

    private ProtobufConstants() {
        // Utility class - prevent instantiation
    }

    // ==================== Package Names ====================

    /**
     * The Google protobuf library package name.
     */
    public static final String PROTOBUF_PACKAGE = "com.google.protobuf";

    // ==================== Class Names ====================

    /**
     * JavaPoet ClassName for {@code com.google.protobuf.Message}.
     * Used as a common supertype for all proto messages.
     */
    public static final ClassName MESSAGE_CLASS = ClassName.get(PROTOBUF_PACKAGE, "Message");

    /**
     * JavaPoet ClassName for {@code com.google.protobuf.ByteString}.
     * Used for bytes fields in protobuf.
     */
    public static final ClassName BYTE_STRING_CLASS = ClassName.get(PROTOBUF_PACKAGE, "ByteString");

    // ==================== Package Suffixes ====================

    /**
     * Suffix appended to API package for implementation classes.
     * Example: {@code com.example.api} becomes {@code com.example.api.impl}
     */
    public static final String IMPL_PACKAGE_SUFFIX = ".impl";

    // ==================== Placeholders ====================

    /**
     * Placeholder for version string in package patterns.
     * Replaced with actual version (e.g., "v1", "v2") during generation.
     */
    public static final String VERSION_PLACEHOLDER = "{version}";

    // ==================== File Comments ====================

    /**
     * Standard comment added to all generated files.
     */
    public static final String GENERATED_FILE_COMMENT = "Generated by proto-wrapper-maven-plugin. DO NOT EDIT.";

    // ==================== Method Prefixes ====================

    /**
     * Prefix for extract methods in abstract classes.
     * Example: {@code extractName}, {@code extractAge}
     */
    public static final String EXTRACT_PREFIX = "extract";

    /**
     * Prefix for presence check methods.
     * Example: {@code hasName}, {@code hasAddress}
     */
    public static final String HAS_PREFIX = "has";

    /**
     * Prefix for getter methods.
     * Example: {@code getName}, {@code getAge}
     */
    public static final String GET_PREFIX = "get";

    /**
     * Prefix for boolean getter methods.
     * Example: {@code isActive}, {@code isEnabled}
     */
    public static final String IS_PREFIX = "is";

    /**
     * Prefix for wrapper factory methods.
     * Example: {@code wrapPerson}, {@code wrapOrder}
     */
    public static final String WRAP_PREFIX = "wrap";
}
