package space.alnovis.protowrapper.generator;

import com.squareup.javapoet.ClassName;

/**
 * Constants for protobuf-related code generation.
 *
 * <p>Centralizes magic strings and commonly used class names to avoid
 * duplication and improve maintainability.</p>
 */
public final class ProtobufConstants {

    private ProtobufConstants() {
        // Utility class
    }

    // Package names
    public static final String PROTOBUF_PACKAGE = "com.google.protobuf";

    // Class names
    public static final ClassName MESSAGE_CLASS = ClassName.get(PROTOBUF_PACKAGE, "Message");
    public static final ClassName BYTE_STRING_CLASS = ClassName.get(PROTOBUF_PACKAGE, "ByteString");

    // Package suffixes
    public static final String IMPL_PACKAGE_SUFFIX = ".impl";

    // Placeholders
    public static final String VERSION_PLACEHOLDER = "{version}";

    // File comments
    public static final String GENERATED_FILE_COMMENT = "Generated by proto-wrapper-maven-plugin. DO NOT EDIT.";

    // Method prefixes
    public static final String EXTRACT_PREFIX = "extract";
    public static final String HAS_PREFIX = "has";
    public static final String GET_PREFIX = "get";
    public static final String IS_PREFIX = "is";
    public static final String WRAP_PREFIX = "wrap";
}
