// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto3.wrapper.api;

import java.lang.IllegalArgumentException;
import java.lang.String;
import java.util.Set;

/**
 * Protocol version constants and utilities.
 *
 * <p>This class provides compile-time constants for all supported protocol versions.
 * Use these constants instead of string literals for type safety.</p>
 *
 * @since 2.1.0
 */
public final class ProtocolVersions {
    /**
     * Version identifier: v1
     */
    public static final String V1 = "v1";

    /**
     * Version identifier: v2
     */
    public static final String V2 = "v2";

    /**
     * Default protocol version.
     *
     * @see #V2
     */
    public static final String DEFAULT = V2;

    private static final Set<String> SUPPORTED = Set.of(V1, V2);

    private ProtocolVersions() {
    }

    /**
     * Get all supported protocol version IDs.
     *
     * @return unmodifiable set of supported version IDs
     */
    public static Set<String> supported() {
        return SUPPORTED;
    }

    /**
     * Check if a version ID is supported.
     *
     * @param versionId the version ID to check
     * @return true if the version is supported
     */
    public static boolean isSupported(String versionId) {
        return SUPPORTED.contains(versionId);
    }

    /**
     * Validate that a version ID is supported.
     *
     * @param versionId the version ID to validate
     * @return the version ID if supported
     * @throws IllegalArgumentException if the version is not supported
     */
    public static String requireSupported(String versionId) {
        if (!isSupported(versionId)) {
            throw new IllegalArgumentException("Unsupported protocol version: " + versionId + ". Supported versions: " + SUPPORTED);
        }
        return versionId;
    }
}
