// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto3.wrapper.v1;

import com.google.protobuf.ByteString;
import com.google.protobuf.Message;
import com.google.protobuf.ProtocolMessageEnum;
import io.alnovis.protowrapper.golden.proto3.v1.AllFields;
import io.alnovis.protowrapper.golden.proto3.wrapper.api.NestedMessage;
import io.alnovis.protowrapper.golden.proto3.wrapper.api.ProtocolVersions;
import io.alnovis.protowrapper.golden.proto3.wrapper.api.TestEnum;
import io.alnovis.protowrapper.golden.proto3.wrapper.api.VersionContext;
import io.alnovis.protowrapper.golden.proto3.wrapper.api.impl.AbstractAllFieldTypes;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Exception;
import java.lang.Float;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.reflect.Method;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * V1 implementation of AllFieldTypes interface.
 *
 * @see AbstractAllFieldTypes
 */
public class AllFieldTypes extends AbstractAllFieldTypes<AllFields.AllFieldTypes> {
    public AllFieldTypes(AllFields.AllFieldTypes proto) {
        super(proto);
    }

    @Override
    protected Integer extractSingularInt32(AllFields.AllFieldTypes proto) {
        return proto.getSingularInt32();
    }

    @Override
    protected Long extractSingularInt64(AllFields.AllFieldTypes proto) {
        return proto.getSingularInt64();
    }

    @Override
    protected Integer extractSingularUint32(AllFields.AllFieldTypes proto) {
        return proto.getSingularUint32();
    }

    @Override
    protected Long extractSingularUint64(AllFields.AllFieldTypes proto) {
        return proto.getSingularUint64();
    }

    @Override
    protected Integer extractSingularSint32(AllFields.AllFieldTypes proto) {
        return proto.getSingularSint32();
    }

    @Override
    protected Long extractSingularSint64(AllFields.AllFieldTypes proto) {
        return proto.getSingularSint64();
    }

    @Override
    protected Integer extractSingularFixed32(AllFields.AllFieldTypes proto) {
        return proto.getSingularFixed32();
    }

    @Override
    protected Long extractSingularFixed64(AllFields.AllFieldTypes proto) {
        return proto.getSingularFixed64();
    }

    @Override
    protected Integer extractSingularSfixed32(AllFields.AllFieldTypes proto) {
        return proto.getSingularSfixed32();
    }

    @Override
    protected Long extractSingularSfixed64(AllFields.AllFieldTypes proto) {
        return proto.getSingularSfixed64();
    }

    @Override
    protected Float extractSingularFloat(AllFields.AllFieldTypes proto) {
        return proto.getSingularFloat();
    }

    @Override
    protected Double extractSingularDouble(AllFields.AllFieldTypes proto) {
        return proto.getSingularDouble();
    }

    @Override
    protected Boolean extractSingularBool(AllFields.AllFieldTypes proto) {
        return proto.getSingularBool();
    }

    @Override
    protected String extractSingularString(AllFields.AllFieldTypes proto) {
        return proto.getSingularString();
    }

    @Override
    protected byte[] extractSingularBytes(AllFields.AllFieldTypes proto) {
        return proto.getSingularBytes().toByteArray();
    }

    @Override
    protected boolean extractHasSingularMessage(AllFields.AllFieldTypes proto) {
        return proto.hasSingularMessage();
    }

    @Override
    protected NestedMessage extractSingularMessage(AllFields.AllFieldTypes proto) {
        return new io.alnovis.protowrapper.golden.proto3.wrapper.v1.NestedMessage(proto.getSingularMessage());
    }

    @Override
    protected TestEnum extractSingularEnum(AllFields.AllFieldTypes proto) {
        return TestEnum.fromProtoValue(proto.getSingularEnum().getNumber());
    }

    @Override
    protected boolean extractHasOptionalInt32(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalInt32();
    }

    @Override
    protected Integer extractOptionalInt32(AllFields.AllFieldTypes proto) {
        return proto.getOptionalInt32();
    }

    @Override
    protected boolean extractHasOptionalInt64(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalInt64();
    }

    @Override
    protected Long extractOptionalInt64(AllFields.AllFieldTypes proto) {
        return proto.getOptionalInt64();
    }

    @Override
    protected boolean extractHasOptionalUint32(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalUint32();
    }

    @Override
    protected Integer extractOptionalUint32(AllFields.AllFieldTypes proto) {
        return proto.getOptionalUint32();
    }

    @Override
    protected boolean extractHasOptionalUint64(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalUint64();
    }

    @Override
    protected Long extractOptionalUint64(AllFields.AllFieldTypes proto) {
        return proto.getOptionalUint64();
    }

    @Override
    protected boolean extractHasOptionalSint32(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalSint32();
    }

    @Override
    protected Integer extractOptionalSint32(AllFields.AllFieldTypes proto) {
        return proto.getOptionalSint32();
    }

    @Override
    protected boolean extractHasOptionalSint64(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalSint64();
    }

    @Override
    protected Long extractOptionalSint64(AllFields.AllFieldTypes proto) {
        return proto.getOptionalSint64();
    }

    @Override
    protected boolean extractHasOptionalFixed32(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalFixed32();
    }

    @Override
    protected Integer extractOptionalFixed32(AllFields.AllFieldTypes proto) {
        return proto.getOptionalFixed32();
    }

    @Override
    protected boolean extractHasOptionalFixed64(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalFixed64();
    }

    @Override
    protected Long extractOptionalFixed64(AllFields.AllFieldTypes proto) {
        return proto.getOptionalFixed64();
    }

    @Override
    protected boolean extractHasOptionalSfixed32(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalSfixed32();
    }

    @Override
    protected Integer extractOptionalSfixed32(AllFields.AllFieldTypes proto) {
        return proto.getOptionalSfixed32();
    }

    @Override
    protected boolean extractHasOptionalSfixed64(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalSfixed64();
    }

    @Override
    protected Long extractOptionalSfixed64(AllFields.AllFieldTypes proto) {
        return proto.getOptionalSfixed64();
    }

    @Override
    protected boolean extractHasOptionalFloat(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalFloat();
    }

    @Override
    protected Float extractOptionalFloat(AllFields.AllFieldTypes proto) {
        return proto.getOptionalFloat();
    }

    @Override
    protected boolean extractHasOptionalDouble(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalDouble();
    }

    @Override
    protected Double extractOptionalDouble(AllFields.AllFieldTypes proto) {
        return proto.getOptionalDouble();
    }

    @Override
    protected boolean extractHasOptionalBool(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalBool();
    }

    @Override
    protected Boolean extractOptionalBool(AllFields.AllFieldTypes proto) {
        return proto.getOptionalBool();
    }

    @Override
    protected boolean extractHasOptionalString(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalString();
    }

    @Override
    protected String extractOptionalString(AllFields.AllFieldTypes proto) {
        return proto.getOptionalString();
    }

    @Override
    protected boolean extractHasOptionalBytes(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalBytes();
    }

    @Override
    protected byte[] extractOptionalBytes(AllFields.AllFieldTypes proto) {
        return proto.getOptionalBytes().toByteArray();
    }

    @Override
    protected boolean extractHasOptionalMessage(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalMessage();
    }

    @Override
    protected NestedMessage extractOptionalMessage(AllFields.AllFieldTypes proto) {
        return new io.alnovis.protowrapper.golden.proto3.wrapper.v1.NestedMessage(proto.getOptionalMessage());
    }

    @Override
    protected boolean extractHasOptionalEnum(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalEnum();
    }

    @Override
    protected TestEnum extractOptionalEnum(AllFields.AllFieldTypes proto) {
        return TestEnum.fromProtoValue(proto.getOptionalEnum().getNumber());
    }

    @Override
    protected List<Integer> extractRepeatedInt32(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedInt32List();
    }

    @Override
    protected List<Long> extractRepeatedInt64(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedInt64List();
    }

    @Override
    protected List<Integer> extractRepeatedUint32(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedUint32List();
    }

    @Override
    protected List<Long> extractRepeatedUint64(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedUint64List();
    }

    @Override
    protected List<Integer> extractRepeatedSint32(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedSint32List();
    }

    @Override
    protected List<Long> extractRepeatedSint64(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedSint64List();
    }

    @Override
    protected List<Integer> extractRepeatedFixed32(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedFixed32List();
    }

    @Override
    protected List<Long> extractRepeatedFixed64(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedFixed64List();
    }

    @Override
    protected List<Integer> extractRepeatedSfixed32(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedSfixed32List();
    }

    @Override
    protected List<Long> extractRepeatedSfixed64(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedSfixed64List();
    }

    @Override
    protected List<Float> extractRepeatedFloat(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedFloatList();
    }

    @Override
    protected List<Double> extractRepeatedDouble(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedDoubleList();
    }

    @Override
    protected List<Boolean> extractRepeatedBool(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedBoolList();
    }

    @Override
    protected List<String> extractRepeatedString(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedStringList();
    }

    @Override
    protected List<byte[]> extractRepeatedBytes(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedBytesList().stream().map(com.google.protobuf.ByteString::toByteArray).collect(java.util.stream.Collectors.toList());
    }

    @Override
    protected List<NestedMessage> extractRepeatedMessage(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedMessageList().stream().map(io.alnovis.protowrapper.golden.proto3.wrapper.v1.NestedMessage::new).collect(java.util.stream.Collectors.toList());
    }

    @Override
    protected List<TestEnum> extractRepeatedEnum(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedEnumList().stream().map(e -> TestEnum.fromProtoValue(e.getNumber())).collect(java.util.stream.Collectors.toList());
    }

    @Override
    protected boolean extractHasOneofInt32(AllFields.AllFieldTypes proto) {
        return proto.hasOneofInt32();
    }

    @Override
    protected Integer extractOneofInt32(AllFields.AllFieldTypes proto) {
        return proto.getOneofInt32();
    }

    @Override
    protected boolean extractHasOneofString(AllFields.AllFieldTypes proto) {
        return proto.hasOneofString();
    }

    @Override
    protected String extractOneofString(AllFields.AllFieldTypes proto) {
        return proto.getOneofString();
    }

    @Override
    protected boolean extractHasOneofMessage(AllFields.AllFieldTypes proto) {
        return proto.hasOneofMessage();
    }

    @Override
    protected NestedMessage extractOneofMessage(AllFields.AllFieldTypes proto) {
        return new io.alnovis.protowrapper.golden.proto3.wrapper.v1.NestedMessage(proto.getOneofMessage());
    }

    @Override
    protected boolean extractHasOneofEnum(AllFields.AllFieldTypes proto) {
        return proto.hasOneofEnum();
    }

    @Override
    protected TestEnum extractOneofEnum(AllFields.AllFieldTypes proto) {
        return TestEnum.fromProtoValue(proto.getOneofEnum().getNumber());
    }

    @Override
    protected Map<String, Integer> extractStringToInt32Map(AllFields.AllFieldTypes proto) {
        return proto.getStringToInt32Map();
    }

    @Override
    protected Map<Integer, String> extractInt32ToStringMap(AllFields.AllFieldTypes proto) {
        return proto.getInt32ToStringMap();
    }

    @Override
    protected Map<String, NestedMessage> extractStringToMessageMap(AllFields.AllFieldTypes proto) {
        Map<String, ?> source = proto.getStringToMessageMap();
        Map<String, NestedMessage> result = new LinkedHashMap<>(source.size());
        source.forEach((k, v) -> result.put(k, new io.alnovis.protowrapper.golden.proto3.wrapper.v1.NestedMessage((io.alnovis.protowrapper.golden.proto3.v1.AllFields.NestedMessage) v)));
        return result;
    }

    @Override
    protected Map<String, TestEnum> extractStringToEnumMap(AllFields.AllFieldTypes proto) {
        Map<String, ?> source = proto.getStringToEnumMap();
        Map<String, TestEnum> result = new LinkedHashMap<>(source.size());
        source.forEach((k, v) -> result.put(k, io.alnovis.protowrapper.golden.proto3.wrapper.api.TestEnum.fromProtoValue(((ProtocolMessageEnum) v).getNumber())));
        return result;
    }

    @Override
    protected Map<Long, String> extractInt64ToStringMap(AllFields.AllFieldTypes proto) {
        return proto.getInt64ToStringMap();
    }

    @Override
    protected io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes.TestOneofCase extractTestOneofCase(
            AllFields.AllFieldTypes proto) {
        Object protoCase = proto.getTestOneofCase();
        return switch (protoCase.toString()) {
            case "ONEOF_INT32" -> io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes.TestOneofCase.ONEOF_INT32;
            case "ONEOF_STRING" -> io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes.TestOneofCase.ONEOF_STRING;
            case "ONEOF_MESSAGE" -> io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes.TestOneofCase.ONEOF_MESSAGE;
            case "ONEOF_ENUM" -> io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes.TestOneofCase.ONEOF_ENUM;
            default -> io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes.TestOneofCase.TEST_ONEOF_NOT_SET;
        } ;
    }

    @Override
    protected byte[] serializeToBytes(AllFields.AllFieldTypes proto) {
        return proto.toByteArray();
    }

    @Override
    protected String extractWrapperVersionId(AllFields.AllFieldTypes proto) {
        return ProtocolVersions.V1;
    }

    public static AllFieldTypes from(AllFields.AllFieldTypes proto) {
        return new AllFieldTypes(proto);
    }

    /**
     * Get the underlying typed proto message.
     * @return AllFields.AllFieldTypes
     */
    @Override
    public AllFields.AllFieldTypes getTypedProto() {
        return proto;
    }

    @Override
    protected VersionContext getVersionContext() {
        return VersionContextV1.INSTANCE;
    }

    @Override
    protected io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes.Builder createBuilder(
            ) {
        return new BuilderImpl(proto.toBuilder());
    }

    @Override
    protected io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes.Builder createEmptyBuilder(
            ) {
        return new BuilderImpl(AllFields.AllFieldTypes.newBuilder());
    }

    public static io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes.Builder newBuilder(
            ) {
        return new BuilderImpl(AllFields.AllFieldTypes.newBuilder());
    }

    private static class BuilderImpl extends AbstractAllFieldTypes.AbstractBuilder<AllFields.AllFieldTypes> {
        private final AllFields.AllFieldTypes.Builder protoBuilder;

        BuilderImpl(AllFields.AllFieldTypes.Builder protoBuilder) {
            this.protoBuilder = protoBuilder;
        }

        @Override
        protected String getVersionId() {
            return ProtocolVersions.V1;
        }

        @Override
        protected void doSetSingularInt32(Integer singularInt32) {
            protoBuilder.setSingularInt32(singularInt32);
        }

        @Override
        protected void doSetSingularInt64(Long singularInt64) {
            protoBuilder.setSingularInt64(singularInt64);
        }

        @Override
        protected void doSetSingularUint32(Integer singularUint32) {
            protoBuilder.setSingularUint32(singularUint32);
        }

        @Override
        protected void doSetSingularUint64(Long singularUint64) {
            protoBuilder.setSingularUint64(singularUint64);
        }

        @Override
        protected void doSetSingularSint32(Integer singularSint32) {
            protoBuilder.setSingularSint32(singularSint32);
        }

        @Override
        protected void doSetSingularSint64(Long singularSint64) {
            protoBuilder.setSingularSint64(singularSint64);
        }

        @Override
        protected void doSetSingularFixed32(Integer singularFixed32) {
            protoBuilder.setSingularFixed32(singularFixed32);
        }

        @Override
        protected void doSetSingularFixed64(Long singularFixed64) {
            protoBuilder.setSingularFixed64(singularFixed64);
        }

        @Override
        protected void doSetSingularSfixed32(Integer singularSfixed32) {
            protoBuilder.setSingularSfixed32(singularSfixed32);
        }

        @Override
        protected void doSetSingularSfixed64(Long singularSfixed64) {
            protoBuilder.setSingularSfixed64(singularSfixed64);
        }

        @Override
        protected void doSetSingularFloat(Float singularFloat) {
            protoBuilder.setSingularFloat(singularFloat);
        }

        @Override
        protected void doSetSingularDouble(Double singularDouble) {
            protoBuilder.setSingularDouble(singularDouble);
        }

        @Override
        protected void doSetSingularBool(Boolean singularBool) {
            protoBuilder.setSingularBool(singularBool);
        }

        @Override
        protected void doSetSingularString(String singularString) {
            protoBuilder.setSingularString(singularString);
        }

        @Override
        protected void doSetSingularBytes(byte[] singularBytes) {
            protoBuilder.setSingularBytes(com.google.protobuf.ByteString.copyFrom(singularBytes));
        }

        @Override
        protected void doSetSingularMessage(NestedMessage singularMessage) {
            protoBuilder.setSingularMessage((io.alnovis.protowrapper.golden.proto3.v1.AllFields.NestedMessage) extractProto(singularMessage));
        }

        @Override
        protected void doClearSingularMessage() {
            protoBuilder.clearSingularMessage();
        }

        @Override
        protected void doSetSingularEnum(TestEnum singularEnum) {
            io.alnovis.protowrapper.golden.proto3.v1.AllFields.TestEnum protoEnumValue = io.alnovis.protowrapper.golden.proto3.v1.AllFields.TestEnum.forNumber(singularEnum.getValue());
            if (protoEnumValue == null) {
                throw new IllegalArgumentException("TestEnum." + singularEnum.name() + " (value=" + singularEnum.getValue() + ") is not supported in protocol version " + getVersionId());
            }
            protoBuilder.setSingularEnum(protoEnumValue);
        }

        @Override
        protected void doSetOptionalInt32(Integer optionalInt32) {
            protoBuilder.setOptionalInt32(optionalInt32);
        }

        @Override
        protected void doClearOptionalInt32() {
            protoBuilder.clearOptionalInt32();
        }

        @Override
        protected void doSetOptionalInt64(Long optionalInt64) {
            protoBuilder.setOptionalInt64(optionalInt64);
        }

        @Override
        protected void doClearOptionalInt64() {
            protoBuilder.clearOptionalInt64();
        }

        @Override
        protected void doSetOptionalUint32(Integer optionalUint32) {
            protoBuilder.setOptionalUint32(optionalUint32);
        }

        @Override
        protected void doClearOptionalUint32() {
            protoBuilder.clearOptionalUint32();
        }

        @Override
        protected void doSetOptionalUint64(Long optionalUint64) {
            protoBuilder.setOptionalUint64(optionalUint64);
        }

        @Override
        protected void doClearOptionalUint64() {
            protoBuilder.clearOptionalUint64();
        }

        @Override
        protected void doSetOptionalSint32(Integer optionalSint32) {
            protoBuilder.setOptionalSint32(optionalSint32);
        }

        @Override
        protected void doClearOptionalSint32() {
            protoBuilder.clearOptionalSint32();
        }

        @Override
        protected void doSetOptionalSint64(Long optionalSint64) {
            protoBuilder.setOptionalSint64(optionalSint64);
        }

        @Override
        protected void doClearOptionalSint64() {
            protoBuilder.clearOptionalSint64();
        }

        @Override
        protected void doSetOptionalFixed32(Integer optionalFixed32) {
            protoBuilder.setOptionalFixed32(optionalFixed32);
        }

        @Override
        protected void doClearOptionalFixed32() {
            protoBuilder.clearOptionalFixed32();
        }

        @Override
        protected void doSetOptionalFixed64(Long optionalFixed64) {
            protoBuilder.setOptionalFixed64(optionalFixed64);
        }

        @Override
        protected void doClearOptionalFixed64() {
            protoBuilder.clearOptionalFixed64();
        }

        @Override
        protected void doSetOptionalSfixed32(Integer optionalSfixed32) {
            protoBuilder.setOptionalSfixed32(optionalSfixed32);
        }

        @Override
        protected void doClearOptionalSfixed32() {
            protoBuilder.clearOptionalSfixed32();
        }

        @Override
        protected void doSetOptionalSfixed64(Long optionalSfixed64) {
            protoBuilder.setOptionalSfixed64(optionalSfixed64);
        }

        @Override
        protected void doClearOptionalSfixed64() {
            protoBuilder.clearOptionalSfixed64();
        }

        @Override
        protected void doSetOptionalFloat(Float optionalFloat) {
            protoBuilder.setOptionalFloat(optionalFloat);
        }

        @Override
        protected void doClearOptionalFloat() {
            protoBuilder.clearOptionalFloat();
        }

        @Override
        protected void doSetOptionalDouble(Double optionalDouble) {
            protoBuilder.setOptionalDouble(optionalDouble);
        }

        @Override
        protected void doClearOptionalDouble() {
            protoBuilder.clearOptionalDouble();
        }

        @Override
        protected void doSetOptionalBool(Boolean optionalBool) {
            protoBuilder.setOptionalBool(optionalBool);
        }

        @Override
        protected void doClearOptionalBool() {
            protoBuilder.clearOptionalBool();
        }

        @Override
        protected void doSetOptionalString(String optionalString) {
            protoBuilder.setOptionalString(optionalString);
        }

        @Override
        protected void doClearOptionalString() {
            protoBuilder.clearOptionalString();
        }

        @Override
        protected void doSetOptionalBytes(byte[] optionalBytes) {
            protoBuilder.setOptionalBytes(com.google.protobuf.ByteString.copyFrom(optionalBytes));
        }

        @Override
        protected void doClearOptionalBytes() {
            protoBuilder.clearOptionalBytes();
        }

        @Override
        protected void doSetOptionalMessage(NestedMessage optionalMessage) {
            protoBuilder.setOptionalMessage((io.alnovis.protowrapper.golden.proto3.v1.AllFields.NestedMessage) extractProto(optionalMessage));
        }

        @Override
        protected void doClearOptionalMessage() {
            protoBuilder.clearOptionalMessage();
        }

        @Override
        protected void doSetOptionalEnum(TestEnum optionalEnum) {
            io.alnovis.protowrapper.golden.proto3.v1.AllFields.TestEnum protoEnumValue = io.alnovis.protowrapper.golden.proto3.v1.AllFields.TestEnum.forNumber(optionalEnum.getValue());
            if (protoEnumValue == null) {
                throw new IllegalArgumentException("TestEnum." + optionalEnum.name() + " (value=" + optionalEnum.getValue() + ") is not supported in protocol version " + getVersionId());
            }
            protoBuilder.setOptionalEnum(protoEnumValue);
        }

        @Override
        protected void doClearOptionalEnum() {
            protoBuilder.clearOptionalEnum();
        }

        @Override
        protected void doAddRepeatedInt32(Integer repeatedInt32) {
            protoBuilder.addRepeatedInt32(repeatedInt32);
        }

        @Override
        protected void doAddAllRepeatedInt32(List<Integer> repeatedInt32) {
            protoBuilder.addAllRepeatedInt32(repeatedInt32);
        }

        @Override
        protected void doSetRepeatedInt32(List<Integer> repeatedInt32) {
            protoBuilder.clearRepeatedInt32();
            protoBuilder.addAllRepeatedInt32(repeatedInt32);
        }

        @Override
        protected void doClearRepeatedInt32() {
            protoBuilder.clearRepeatedInt32();
        }

        @Override
        protected void doAddRepeatedInt64(Long repeatedInt64) {
            protoBuilder.addRepeatedInt64(repeatedInt64);
        }

        @Override
        protected void doAddAllRepeatedInt64(List<Long> repeatedInt64) {
            protoBuilder.addAllRepeatedInt64(repeatedInt64);
        }

        @Override
        protected void doSetRepeatedInt64(List<Long> repeatedInt64) {
            protoBuilder.clearRepeatedInt64();
            protoBuilder.addAllRepeatedInt64(repeatedInt64);
        }

        @Override
        protected void doClearRepeatedInt64() {
            protoBuilder.clearRepeatedInt64();
        }

        @Override
        protected void doAddRepeatedUint32(Integer repeatedUint32) {
            protoBuilder.addRepeatedUint32(repeatedUint32);
        }

        @Override
        protected void doAddAllRepeatedUint32(List<Integer> repeatedUint32) {
            protoBuilder.addAllRepeatedUint32(repeatedUint32);
        }

        @Override
        protected void doSetRepeatedUint32(List<Integer> repeatedUint32) {
            protoBuilder.clearRepeatedUint32();
            protoBuilder.addAllRepeatedUint32(repeatedUint32);
        }

        @Override
        protected void doClearRepeatedUint32() {
            protoBuilder.clearRepeatedUint32();
        }

        @Override
        protected void doAddRepeatedUint64(Long repeatedUint64) {
            protoBuilder.addRepeatedUint64(repeatedUint64);
        }

        @Override
        protected void doAddAllRepeatedUint64(List<Long> repeatedUint64) {
            protoBuilder.addAllRepeatedUint64(repeatedUint64);
        }

        @Override
        protected void doSetRepeatedUint64(List<Long> repeatedUint64) {
            protoBuilder.clearRepeatedUint64();
            protoBuilder.addAllRepeatedUint64(repeatedUint64);
        }

        @Override
        protected void doClearRepeatedUint64() {
            protoBuilder.clearRepeatedUint64();
        }

        @Override
        protected void doAddRepeatedSint32(Integer repeatedSint32) {
            protoBuilder.addRepeatedSint32(repeatedSint32);
        }

        @Override
        protected void doAddAllRepeatedSint32(List<Integer> repeatedSint32) {
            protoBuilder.addAllRepeatedSint32(repeatedSint32);
        }

        @Override
        protected void doSetRepeatedSint32(List<Integer> repeatedSint32) {
            protoBuilder.clearRepeatedSint32();
            protoBuilder.addAllRepeatedSint32(repeatedSint32);
        }

        @Override
        protected void doClearRepeatedSint32() {
            protoBuilder.clearRepeatedSint32();
        }

        @Override
        protected void doAddRepeatedSint64(Long repeatedSint64) {
            protoBuilder.addRepeatedSint64(repeatedSint64);
        }

        @Override
        protected void doAddAllRepeatedSint64(List<Long> repeatedSint64) {
            protoBuilder.addAllRepeatedSint64(repeatedSint64);
        }

        @Override
        protected void doSetRepeatedSint64(List<Long> repeatedSint64) {
            protoBuilder.clearRepeatedSint64();
            protoBuilder.addAllRepeatedSint64(repeatedSint64);
        }

        @Override
        protected void doClearRepeatedSint64() {
            protoBuilder.clearRepeatedSint64();
        }

        @Override
        protected void doAddRepeatedFixed32(Integer repeatedFixed32) {
            protoBuilder.addRepeatedFixed32(repeatedFixed32);
        }

        @Override
        protected void doAddAllRepeatedFixed32(List<Integer> repeatedFixed32) {
            protoBuilder.addAllRepeatedFixed32(repeatedFixed32);
        }

        @Override
        protected void doSetRepeatedFixed32(List<Integer> repeatedFixed32) {
            protoBuilder.clearRepeatedFixed32();
            protoBuilder.addAllRepeatedFixed32(repeatedFixed32);
        }

        @Override
        protected void doClearRepeatedFixed32() {
            protoBuilder.clearRepeatedFixed32();
        }

        @Override
        protected void doAddRepeatedFixed64(Long repeatedFixed64) {
            protoBuilder.addRepeatedFixed64(repeatedFixed64);
        }

        @Override
        protected void doAddAllRepeatedFixed64(List<Long> repeatedFixed64) {
            protoBuilder.addAllRepeatedFixed64(repeatedFixed64);
        }

        @Override
        protected void doSetRepeatedFixed64(List<Long> repeatedFixed64) {
            protoBuilder.clearRepeatedFixed64();
            protoBuilder.addAllRepeatedFixed64(repeatedFixed64);
        }

        @Override
        protected void doClearRepeatedFixed64() {
            protoBuilder.clearRepeatedFixed64();
        }

        @Override
        protected void doAddRepeatedSfixed32(Integer repeatedSfixed32) {
            protoBuilder.addRepeatedSfixed32(repeatedSfixed32);
        }

        @Override
        protected void doAddAllRepeatedSfixed32(List<Integer> repeatedSfixed32) {
            protoBuilder.addAllRepeatedSfixed32(repeatedSfixed32);
        }

        @Override
        protected void doSetRepeatedSfixed32(List<Integer> repeatedSfixed32) {
            protoBuilder.clearRepeatedSfixed32();
            protoBuilder.addAllRepeatedSfixed32(repeatedSfixed32);
        }

        @Override
        protected void doClearRepeatedSfixed32() {
            protoBuilder.clearRepeatedSfixed32();
        }

        @Override
        protected void doAddRepeatedSfixed64(Long repeatedSfixed64) {
            protoBuilder.addRepeatedSfixed64(repeatedSfixed64);
        }

        @Override
        protected void doAddAllRepeatedSfixed64(List<Long> repeatedSfixed64) {
            protoBuilder.addAllRepeatedSfixed64(repeatedSfixed64);
        }

        @Override
        protected void doSetRepeatedSfixed64(List<Long> repeatedSfixed64) {
            protoBuilder.clearRepeatedSfixed64();
            protoBuilder.addAllRepeatedSfixed64(repeatedSfixed64);
        }

        @Override
        protected void doClearRepeatedSfixed64() {
            protoBuilder.clearRepeatedSfixed64();
        }

        @Override
        protected void doAddRepeatedFloat(Float repeatedFloat) {
            protoBuilder.addRepeatedFloat(repeatedFloat);
        }

        @Override
        protected void doAddAllRepeatedFloat(List<Float> repeatedFloat) {
            protoBuilder.addAllRepeatedFloat(repeatedFloat);
        }

        @Override
        protected void doSetRepeatedFloat(List<Float> repeatedFloat) {
            protoBuilder.clearRepeatedFloat();
            protoBuilder.addAllRepeatedFloat(repeatedFloat);
        }

        @Override
        protected void doClearRepeatedFloat() {
            protoBuilder.clearRepeatedFloat();
        }

        @Override
        protected void doAddRepeatedDouble(Double repeatedDouble) {
            protoBuilder.addRepeatedDouble(repeatedDouble);
        }

        @Override
        protected void doAddAllRepeatedDouble(List<Double> repeatedDouble) {
            protoBuilder.addAllRepeatedDouble(repeatedDouble);
        }

        @Override
        protected void doSetRepeatedDouble(List<Double> repeatedDouble) {
            protoBuilder.clearRepeatedDouble();
            protoBuilder.addAllRepeatedDouble(repeatedDouble);
        }

        @Override
        protected void doClearRepeatedDouble() {
            protoBuilder.clearRepeatedDouble();
        }

        @Override
        protected void doAddRepeatedBool(Boolean repeatedBool) {
            protoBuilder.addRepeatedBool(repeatedBool);
        }

        @Override
        protected void doAddAllRepeatedBool(List<Boolean> repeatedBool) {
            protoBuilder.addAllRepeatedBool(repeatedBool);
        }

        @Override
        protected void doSetRepeatedBool(List<Boolean> repeatedBool) {
            protoBuilder.clearRepeatedBool();
            protoBuilder.addAllRepeatedBool(repeatedBool);
        }

        @Override
        protected void doClearRepeatedBool() {
            protoBuilder.clearRepeatedBool();
        }

        @Override
        protected void doAddRepeatedString(String repeatedString) {
            protoBuilder.addRepeatedString(repeatedString);
        }

        @Override
        protected void doAddAllRepeatedString(List<String> repeatedString) {
            protoBuilder.addAllRepeatedString(repeatedString);
        }

        @Override
        protected void doSetRepeatedString(List<String> repeatedString) {
            protoBuilder.clearRepeatedString();
            protoBuilder.addAllRepeatedString(repeatedString);
        }

        @Override
        protected void doClearRepeatedString() {
            protoBuilder.clearRepeatedString();
        }

        @Override
        protected void doAddRepeatedBytes(byte[] repeatedBytes) {
            protoBuilder.addRepeatedBytes(ByteString.copyFrom(repeatedBytes));
        }

        @Override
        protected void doAddAllRepeatedBytes(List<byte[]> repeatedBytes) {
            repeatedBytes.forEach(e -> protoBuilder.addRepeatedBytes(ByteString.copyFrom(e)));
        }

        @Override
        protected void doSetRepeatedBytes(List<byte[]> repeatedBytes) {
            protoBuilder.clearRepeatedBytes();
            repeatedBytes.forEach(e -> protoBuilder.addRepeatedBytes(ByteString.copyFrom(e)));
        }

        @Override
        protected void doClearRepeatedBytes() {
            protoBuilder.clearRepeatedBytes();
        }

        @Override
        protected void doAddRepeatedMessage(NestedMessage repeatedMessage) {
            protoBuilder.addRepeatedMessage((io.alnovis.protowrapper.golden.proto3.v1.AllFields.NestedMessage) extractProto(repeatedMessage));
        }

        @Override
        protected void doAddAllRepeatedMessage(List<NestedMessage> repeatedMessage) {
            repeatedMessage.forEach(e -> protoBuilder.addRepeatedMessage((io.alnovis.protowrapper.golden.proto3.v1.AllFields.NestedMessage) extractProto(e)));
        }

        @Override
        protected void doSetRepeatedMessage(List<NestedMessage> repeatedMessage) {
            protoBuilder.clearRepeatedMessage();
            repeatedMessage.forEach(e -> protoBuilder.addRepeatedMessage((io.alnovis.protowrapper.golden.proto3.v1.AllFields.NestedMessage) extractProto(e)));
        }

        @Override
        protected void doClearRepeatedMessage() {
            protoBuilder.clearRepeatedMessage();
        }

        @Override
        protected void doAddRepeatedEnum(TestEnum repeatedEnum) {
            protoBuilder.addRepeatedEnum(io.alnovis.protowrapper.golden.proto3.v1.AllFields.TestEnum.forNumber(repeatedEnum.getValue()));
        }

        @Override
        protected void doAddAllRepeatedEnum(List<TestEnum> repeatedEnum) {
            repeatedEnum.forEach(e -> protoBuilder.addRepeatedEnum(io.alnovis.protowrapper.golden.proto3.v1.AllFields.TestEnum.forNumber(e.getValue())));
        }

        @Override
        protected void doSetRepeatedEnum(List<TestEnum> repeatedEnum) {
            protoBuilder.clearRepeatedEnum();
            repeatedEnum.forEach(e -> protoBuilder.addRepeatedEnum(io.alnovis.protowrapper.golden.proto3.v1.AllFields.TestEnum.forNumber(e.getValue())));
        }

        @Override
        protected void doClearRepeatedEnum() {
            protoBuilder.clearRepeatedEnum();
        }

        @Override
        protected void doSetOneofInt32(Integer oneofInt32) {
            protoBuilder.setOneofInt32(oneofInt32);
        }

        @Override
        protected void doClearOneofInt32() {
            protoBuilder.clearOneofInt32();
        }

        @Override
        protected void doSetOneofString(String oneofString) {
            protoBuilder.setOneofString(oneofString);
        }

        @Override
        protected void doClearOneofString() {
            protoBuilder.clearOneofString();
        }

        @Override
        protected void doSetOneofMessage(NestedMessage oneofMessage) {
            protoBuilder.setOneofMessage((io.alnovis.protowrapper.golden.proto3.v1.AllFields.NestedMessage) extractProto(oneofMessage));
        }

        @Override
        protected void doClearOneofMessage() {
            protoBuilder.clearOneofMessage();
        }

        @Override
        protected void doSetOneofEnum(TestEnum oneofEnum) {
            io.alnovis.protowrapper.golden.proto3.v1.AllFields.TestEnum protoEnumValue = io.alnovis.protowrapper.golden.proto3.v1.AllFields.TestEnum.forNumber(oneofEnum.getValue());
            if (protoEnumValue == null) {
                throw new IllegalArgumentException("TestEnum." + oneofEnum.name() + " (value=" + oneofEnum.getValue() + ") is not supported in protocol version " + getVersionId());
            }
            protoBuilder.setOneofEnum(protoEnumValue);
        }

        @Override
        protected void doClearOneofEnum() {
            protoBuilder.clearOneofEnum();
        }

        @Override
        protected void doPutStringToInt32(String key, int value) {
            protoBuilder.putStringToInt32(key, value);
        }

        @Override
        protected void doPutAllStringToInt32(Map<String, Integer> values) {
            protoBuilder.putAllStringToInt32(values);
        }

        @Override
        protected void doRemoveStringToInt32(String key) {
            protoBuilder.removeStringToInt32(key);
        }

        @Override
        protected void doClearStringToInt32() {
            protoBuilder.clearStringToInt32();
        }

        @Override
        protected Map<String, Integer> doGetStringToInt32Map() {
            return protoBuilder.getStringToInt32Map();
        }

        @Override
        protected void doPutInt32ToString(int key, String value) {
            protoBuilder.putInt32ToString(key, value);
        }

        @Override
        protected void doPutAllInt32ToString(Map<Integer, String> values) {
            protoBuilder.putAllInt32ToString(values);
        }

        @Override
        protected void doRemoveInt32ToString(int key) {
            protoBuilder.removeInt32ToString(key);
        }

        @Override
        protected void doClearInt32ToString() {
            protoBuilder.clearInt32ToString();
        }

        @Override
        protected Map<Integer, String> doGetInt32ToStringMap() {
            return protoBuilder.getInt32ToStringMap();
        }

        @Override
        protected void doPutStringToMessage(String key, NestedMessage value) {
            protoBuilder.putStringToMessage(key, (io.alnovis.protowrapper.golden.proto3.v1.AllFields.NestedMessage) extractProto(value));
        }

        @Override
        protected void doPutAllStringToMessage(Map<String, NestedMessage> values) {
            values.forEach((k, v) -> doPutStringToMessage(k, v));
        }

        @Override
        protected void doRemoveStringToMessage(String key) {
            protoBuilder.removeStringToMessage(key);
        }

        @Override
        protected void doClearStringToMessage() {
            protoBuilder.clearStringToMessage();
        }

        @Override
        protected Map<String, NestedMessage> doGetStringToMessageMap() {
            Map<String, ?> source = protoBuilder.getStringToMessageMap();
            Map<String, NestedMessage> result = new LinkedHashMap<>(source.size());
            source.forEach((k, v) -> result.put(k, new io.alnovis.protowrapper.golden.proto3.wrapper.v1.NestedMessage((io.alnovis.protowrapper.golden.proto3.v1.AllFields.NestedMessage) v)));
            return result;
        }

        @Override
        protected void doPutStringToEnum(String key, TestEnum value) {
            protoBuilder.putStringToEnum(key, io.alnovis.protowrapper.golden.proto3.v1.AllFields.TestEnum.forNumber(value.getValue()));
        }

        @Override
        protected void doPutAllStringToEnum(Map<String, TestEnum> values) {
            values.forEach((k, v) -> doPutStringToEnum(k, v));
        }

        @Override
        protected void doRemoveStringToEnum(String key) {
            protoBuilder.removeStringToEnum(key);
        }

        @Override
        protected void doClearStringToEnum() {
            protoBuilder.clearStringToEnum();
        }

        @Override
        protected Map<String, TestEnum> doGetStringToEnumMap() {
            Map<String, ?> source = protoBuilder.getStringToEnumMap();
            Map<String, TestEnum> result = new LinkedHashMap<>(source.size());
            source.forEach((k, v) -> result.put(k, io.alnovis.protowrapper.golden.proto3.wrapper.api.TestEnum.fromProtoValue(((ProtocolMessageEnum) v).getNumber())));
            return result;
        }

        @Override
        protected void doPutInt64ToString(long key, String value) {
            protoBuilder.putInt64ToString(key, value);
        }

        @Override
        protected void doPutAllInt64ToString(Map<Long, String> values) {
            protoBuilder.putAllInt64ToString(values);
        }

        @Override
        protected void doRemoveInt64ToString(long key) {
            protoBuilder.removeInt64ToString(key);
        }

        @Override
        protected void doClearInt64ToString() {
            protoBuilder.clearInt64ToString();
        }

        @Override
        protected Map<Long, String> doGetInt64ToStringMap() {
            return protoBuilder.getInt64ToStringMap();
        }

        @Override
        protected void doClearTestOneof() {
            protoBuilder.clearTestOneof();
        }

        @Override
        protected io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes doBuild() {
            return new AllFieldTypes(protoBuilder.build());
        }

        private Message extractProto(Object wrapper) {
            if (wrapper == null) {
                return null;
            }
            try {
                Method method = wrapper.getClass().getMethod("getTypedProto");
                return (Message) method.invoke(wrapper);
            } catch (Exception e) {
                throw new RuntimeException("Cannot extract proto from " + wrapper.getClass(), e);
            }
        }
    }
}
