// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto2.wrapper.metadata;

import io.alnovis.protowrapper.golden.proto2.wrapper.api.ProtocolVersions;
import io.alnovis.protowrapper.runtime.VersionSchemaDiff;
import java.lang.Override;
import java.lang.String;
import java.util.List;

/**
 * Schema diff from v1 to v2.
 *
 * @since 2.3.0
 */
public final class SchemaDiffV1ToV2 implements VersionSchemaDiff {
    public static final SchemaDiffV1ToV2 INSTANCE = new SchemaDiffV1ToV2();

    private static final String FROM_VERSION = ProtocolVersions.V1;

    private static final String TO_VERSION = ProtocolVersions.V2;

    private static final List<VersionSchemaDiff.FieldChange> FIELD_CHANGES = List.of();

    private static final List<VersionSchemaDiff.EnumChange> ENUM_CHANGES = List.of();

    private SchemaDiffV1ToV2() {
    }

    @Override
    public String getFromVersion() {
        return FROM_VERSION;
    }

    @Override
    public String getToVersion() {
        return TO_VERSION;
    }

    @Override
    public List<VersionSchemaDiff.FieldChange> getFieldChanges() {
        return FIELD_CHANGES;
    }

    @Override
    public List<VersionSchemaDiff.EnumChange> getEnumChanges() {
        return ENUM_CHANGES;
    }
}
