// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto2.wrapper.metadata;

import io.alnovis.protowrapper.golden.proto2.wrapper.api.ProtocolVersions;
import io.alnovis.protowrapper.runtime.SchemaInfo;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Map;

/**
 * Schema metadata for protocol version v1.
 *
 * <p>Provides runtime access to enum values and message field information.</p>
 *
 * @since 2.3.0
 */
public final class SchemaInfoV1 implements SchemaInfo {
    /**
     * Singleton instance.
     */
    public static final SchemaInfoV1 INSTANCE = new SchemaInfoV1();

    private static final String VERSION_ID = ProtocolVersions.V1;

    private static final Map<String, SchemaInfo.EnumInfo> ENUMS = Map.ofEntries(
        Map.entry("TestEnum", createEnum("TestEnum", "io.alnovis.protowrapper.golden.proto2.v1.TestEnum", List.of(
            new SchemaInfo.EnumValue("UNKNOWN", 0),
            new SchemaInfo.EnumValue("VALUE_ONE", 1),
            new SchemaInfo.EnumValue("VALUE_TWO", 2),
            new SchemaInfo.EnumValue("VALUE_THREE", 3))))
    );

    private static final Map<String, SchemaInfo.MessageInfo> MESSAGES = Map.ofEntries(
        Map.entry("NestedMessage", createMessage("NestedMessage", "io.alnovis.protowrapper.golden.proto2.v1.NestedMessage")),
        Map.entry("AllFieldTypes", createMessage("AllFieldTypes", "io.alnovis.protowrapper.golden.proto2.v1.AllFieldTypes"))
    );

    private SchemaInfoV1() {
    }

    private static SchemaInfo.EnumInfo createEnum(String name, String fullName,
            List<SchemaInfo.EnumValue> values) {
        return new EnumInfoImpl(name, fullName, values);
    }

    private static SchemaInfo.MessageInfo createMessage(String name, String fullName) {
        return new MessageInfoImpl(name, fullName);
    }

    @Override
    public String getVersionId() {
        return VERSION_ID;
    }

    @Override
    public Map<String, SchemaInfo.EnumInfo> getEnums() {
        return ENUMS;
    }

    @Override
    public Map<String, SchemaInfo.MessageInfo> getMessages() {
        return MESSAGES;
    }

    private static final class EnumInfoImpl implements SchemaInfo.EnumInfo {
        private final String name;

        private final String fullName;

        private final List<SchemaInfo.EnumValue> values;

        EnumInfoImpl(String name, String fullName, List<SchemaInfo.EnumValue> values) {
            this.name = name;
            this.fullName = fullName;
            this.values = values;
        }

        @Override
        public String getName() {
            return name;
        }

        @Override
        public String getFullName() {
            return fullName;
        }

        @Override
        public List<SchemaInfo.EnumValue> getValues() {
            return values;
        }
    }

    private static final class MessageInfoImpl implements SchemaInfo.MessageInfo {
        private final String name;

        private final String fullName;

        MessageInfoImpl(String name, String fullName) {
            this.name = name;
            this.fullName = fullName;
        }

        @Override
        public String getName() {
            return name;
        }

        @Override
        public String getFullName() {
            return fullName;
        }

        @Override
        public Map<String, SchemaInfo.FieldInfo> getFields() {
            return Map.of();
        }
    }
}
