// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto3.wrapper.v2;

import io.alnovis.protowrapper.golden.proto3.v2.AllFields;
import io.alnovis.protowrapper.golden.proto3.wrapper.api.ProtocolVersions;
import io.alnovis.protowrapper.golden.proto3.wrapper.api.VersionContext;
import io.alnovis.protowrapper.golden.proto3.wrapper.api.impl.AbstractNestedMessage;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;

/**
 * V2 implementation of NestedMessage interface.
 *
 * @see AbstractNestedMessage
 */
public class NestedMessage extends AbstractNestedMessage<AllFields.NestedMessage> {
    public NestedMessage(AllFields.NestedMessage proto) {
        super(proto);
    }

    @Override
    protected Integer extractId(AllFields.NestedMessage proto) {
        return proto.getId();
    }

    @Override
    protected String extractName(AllFields.NestedMessage proto) {
        return proto.getName();
    }

    @Override
    protected byte[] serializeToBytes(AllFields.NestedMessage proto) {
        return proto.toByteArray();
    }

    @Override
    protected String extractWrapperVersionId(AllFields.NestedMessage proto) {
        return ProtocolVersions.V2;
    }

    public static NestedMessage from(AllFields.NestedMessage proto) {
        return new NestedMessage(proto);
    }

    /**
     * Get the underlying typed proto message.
     * @return AllFields.NestedMessage
     */
    @Override
    public AllFields.NestedMessage getTypedProto() {
        return proto;
    }

    @Override
    protected VersionContext getVersionContext() {
        return VersionContextV2.INSTANCE;
    }

    @Override
    protected io.alnovis.protowrapper.golden.proto3.wrapper.api.NestedMessage.Builder createBuilder(
            ) {
        return new BuilderImpl(proto.toBuilder());
    }

    @Override
    protected io.alnovis.protowrapper.golden.proto3.wrapper.api.NestedMessage.Builder createEmptyBuilder(
            ) {
        return new BuilderImpl(AllFields.NestedMessage.newBuilder());
    }

    public static io.alnovis.protowrapper.golden.proto3.wrapper.api.NestedMessage.Builder newBuilder(
            ) {
        return new BuilderImpl(AllFields.NestedMessage.newBuilder());
    }

    private static class BuilderImpl extends AbstractNestedMessage.AbstractBuilder<AllFields.NestedMessage> {
        private final AllFields.NestedMessage.Builder protoBuilder;

        BuilderImpl(AllFields.NestedMessage.Builder protoBuilder) {
            this.protoBuilder = protoBuilder;
        }

        @Override
        protected String getVersionId() {
            return ProtocolVersions.V2;
        }

        @Override
        protected void doSetId(Integer id) {
            protoBuilder.setId(id);
        }

        @Override
        protected void doSetName(String name) {
            protoBuilder.setName(name);
        }

        @Override
        protected io.alnovis.protowrapper.golden.proto3.wrapper.api.NestedMessage doBuild() {
            return new NestedMessage(protoBuilder.build());
        }
    }
}
