// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto3.wrapper.v2;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.Message;
import io.alnovis.protowrapper.golden.proto3.v2.AllFields;
import io.alnovis.protowrapper.golden.proto3.wrapper.api.ProtocolVersions;
import io.alnovis.protowrapper.golden.proto3.wrapper.api.VersionContext;
import io.alnovis.protowrapper.golden.proto3.wrapper.metadata.SchemaDiffV1ToV2;
import io.alnovis.protowrapper.golden.proto3.wrapper.metadata.SchemaInfoV2;
import io.alnovis.protowrapper.runtime.SchemaInfo;
import io.alnovis.protowrapper.runtime.VersionSchemaDiff;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * V2 implementation of VersionContext.
 */
public final class VersionContextV2 implements VersionContext {
    public static final VersionContextV2 INSTANCE = new VersionContextV2();

    private VersionContextV2() {
    }

    @Override
    public String getVersionId() {
        return ProtocolVersions.V2;
    }

    @Override
    public SchemaInfo getSchemaInfo() {
        return SchemaInfoV2.INSTANCE;
    }

    @Override
    public Optional<VersionSchemaDiff> getDiffFrom(String previousVersion) {
        if (ProtocolVersions.V1.equals(previousVersion)) {
            return Optional.of(SchemaDiffV1ToV2.INSTANCE);
        }
        return Optional.empty();
    }

    @Override
    public io.alnovis.protowrapper.golden.proto3.wrapper.api.NestedMessage wrapNestedMessage(
            Message proto) {
        if (proto == null) {
            return null;
        }
        return new NestedMessage((AllFields.NestedMessage) proto);
    }

    @Override
    public io.alnovis.protowrapper.golden.proto3.wrapper.api.NestedMessage parseNestedMessageFromBytes(
            byte[] bytes) throws InvalidProtocolBufferException {
        if (bytes == null) {
            return null;
        }
        return new NestedMessage(AllFields.NestedMessage.parseFrom(bytes));
    }

    @Override
    public io.alnovis.protowrapper.golden.proto3.wrapper.api.NestedMessage parsePartialNestedMessageFromBytes(
            byte[] bytes) throws InvalidProtocolBufferException {
        if (bytes == null) {
            return null;
        }
        return new NestedMessage(AllFields.NestedMessage.newBuilder().mergeFrom(bytes).buildPartial());
    }

    @Override
    public io.alnovis.protowrapper.golden.proto3.wrapper.api.NestedMessage.Builder newNestedMessageBuilder(
            ) {
        return NestedMessage.newBuilder();
    }

    @Override
    public io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes wrapAllFieldTypes(
            Message proto) {
        if (proto == null) {
            return null;
        }
        return new AllFieldTypes((AllFields.AllFieldTypes) proto);
    }

    @Override
    public io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes parseAllFieldTypesFromBytes(
            byte[] bytes) throws InvalidProtocolBufferException {
        if (bytes == null) {
            return null;
        }
        return new AllFieldTypes(AllFields.AllFieldTypes.parseFrom(bytes));
    }

    @Override
    public io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes parsePartialAllFieldTypesFromBytes(
            byte[] bytes) throws InvalidProtocolBufferException {
        if (bytes == null) {
            return null;
        }
        return new AllFieldTypes(AllFields.AllFieldTypes.newBuilder().mergeFrom(bytes).buildPartial());
    }

    @Override
    public io.alnovis.protowrapper.golden.proto3.wrapper.api.AllFieldTypes.Builder newAllFieldTypesBuilder(
            ) {
        return AllFieldTypes.newBuilder();
    }
}
