// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto2.wrapper.v2;

import com.google.protobuf.ByteString;
import com.google.protobuf.Message;
import com.google.protobuf.ProtocolMessageEnum;
import io.alnovis.protowrapper.golden.proto2.v2.AllFields;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.NestedMessage;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.ProtocolVersions;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.TestEnum;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.VersionContext;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.impl.AbstractAllFieldTypes;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Exception;
import java.lang.Float;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.reflect.Method;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * V2 implementation of AllFieldTypes interface.
 *
 * @see AbstractAllFieldTypes
 */
public class AllFieldTypes extends AbstractAllFieldTypes<AllFields.AllFieldTypes> {
    public AllFieldTypes(AllFields.AllFieldTypes proto) {
        super(proto);
    }

    @Override
    protected boolean extractHasRequiredInt32(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredInt32();
    }

    @Override
    protected int extractRequiredInt32(AllFields.AllFieldTypes proto) {
        return proto.getRequiredInt32();
    }

    @Override
    protected boolean extractHasRequiredInt64(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredInt64();
    }

    @Override
    protected long extractRequiredInt64(AllFields.AllFieldTypes proto) {
        return proto.getRequiredInt64();
    }

    @Override
    protected boolean extractHasRequiredUint32(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredUint32();
    }

    @Override
    protected int extractRequiredUint32(AllFields.AllFieldTypes proto) {
        return proto.getRequiredUint32();
    }

    @Override
    protected boolean extractHasRequiredUint64(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredUint64();
    }

    @Override
    protected long extractRequiredUint64(AllFields.AllFieldTypes proto) {
        return proto.getRequiredUint64();
    }

    @Override
    protected boolean extractHasRequiredSint32(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredSint32();
    }

    @Override
    protected int extractRequiredSint32(AllFields.AllFieldTypes proto) {
        return proto.getRequiredSint32();
    }

    @Override
    protected boolean extractHasRequiredSint64(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredSint64();
    }

    @Override
    protected long extractRequiredSint64(AllFields.AllFieldTypes proto) {
        return proto.getRequiredSint64();
    }

    @Override
    protected boolean extractHasRequiredFixed32(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredFixed32();
    }

    @Override
    protected int extractRequiredFixed32(AllFields.AllFieldTypes proto) {
        return proto.getRequiredFixed32();
    }

    @Override
    protected boolean extractHasRequiredFixed64(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredFixed64();
    }

    @Override
    protected long extractRequiredFixed64(AllFields.AllFieldTypes proto) {
        return proto.getRequiredFixed64();
    }

    @Override
    protected boolean extractHasRequiredSfixed32(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredSfixed32();
    }

    @Override
    protected int extractRequiredSfixed32(AllFields.AllFieldTypes proto) {
        return proto.getRequiredSfixed32();
    }

    @Override
    protected boolean extractHasRequiredSfixed64(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredSfixed64();
    }

    @Override
    protected long extractRequiredSfixed64(AllFields.AllFieldTypes proto) {
        return proto.getRequiredSfixed64();
    }

    @Override
    protected boolean extractHasRequiredFloat(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredFloat();
    }

    @Override
    protected float extractRequiredFloat(AllFields.AllFieldTypes proto) {
        return proto.getRequiredFloat();
    }

    @Override
    protected boolean extractHasRequiredDouble(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredDouble();
    }

    @Override
    protected double extractRequiredDouble(AllFields.AllFieldTypes proto) {
        return proto.getRequiredDouble();
    }

    @Override
    protected boolean extractHasRequiredBool(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredBool();
    }

    @Override
    protected boolean extractRequiredBool(AllFields.AllFieldTypes proto) {
        return proto.getRequiredBool();
    }

    @Override
    protected boolean extractHasRequiredString(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredString();
    }

    @Override
    protected String extractRequiredString(AllFields.AllFieldTypes proto) {
        return proto.getRequiredString();
    }

    @Override
    protected boolean extractHasRequiredBytes(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredBytes();
    }

    @Override
    protected byte[] extractRequiredBytes(AllFields.AllFieldTypes proto) {
        return proto.getRequiredBytes().toByteArray();
    }

    @Override
    protected boolean extractHasRequiredMessage(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredMessage();
    }

    @Override
    protected NestedMessage extractRequiredMessage(AllFields.AllFieldTypes proto) {
        return new io.alnovis.protowrapper.golden.proto2.wrapper.v2.NestedMessage(proto.getRequiredMessage());
    }

    @Override
    protected boolean extractHasRequiredEnum(AllFields.AllFieldTypes proto) {
        return proto.hasRequiredEnum();
    }

    @Override
    protected TestEnum extractRequiredEnum(AllFields.AllFieldTypes proto) {
        return TestEnum.fromProtoValue(proto.getRequiredEnum().getNumber());
    }

    @Override
    protected boolean extractHasOptionalInt32(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalInt32();
    }

    @Override
    protected Integer extractOptionalInt32(AllFields.AllFieldTypes proto) {
        return proto.getOptionalInt32();
    }

    @Override
    protected boolean extractHasOptionalInt64(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalInt64();
    }

    @Override
    protected Long extractOptionalInt64(AllFields.AllFieldTypes proto) {
        return proto.getOptionalInt64();
    }

    @Override
    protected boolean extractHasOptionalUint32(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalUint32();
    }

    @Override
    protected Integer extractOptionalUint32(AllFields.AllFieldTypes proto) {
        return proto.getOptionalUint32();
    }

    @Override
    protected boolean extractHasOptionalUint64(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalUint64();
    }

    @Override
    protected Long extractOptionalUint64(AllFields.AllFieldTypes proto) {
        return proto.getOptionalUint64();
    }

    @Override
    protected boolean extractHasOptionalSint32(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalSint32();
    }

    @Override
    protected Integer extractOptionalSint32(AllFields.AllFieldTypes proto) {
        return proto.getOptionalSint32();
    }

    @Override
    protected boolean extractHasOptionalSint64(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalSint64();
    }

    @Override
    protected Long extractOptionalSint64(AllFields.AllFieldTypes proto) {
        return proto.getOptionalSint64();
    }

    @Override
    protected boolean extractHasOptionalFixed32(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalFixed32();
    }

    @Override
    protected Integer extractOptionalFixed32(AllFields.AllFieldTypes proto) {
        return proto.getOptionalFixed32();
    }

    @Override
    protected boolean extractHasOptionalFixed64(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalFixed64();
    }

    @Override
    protected Long extractOptionalFixed64(AllFields.AllFieldTypes proto) {
        return proto.getOptionalFixed64();
    }

    @Override
    protected boolean extractHasOptionalSfixed32(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalSfixed32();
    }

    @Override
    protected Integer extractOptionalSfixed32(AllFields.AllFieldTypes proto) {
        return proto.getOptionalSfixed32();
    }

    @Override
    protected boolean extractHasOptionalSfixed64(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalSfixed64();
    }

    @Override
    protected Long extractOptionalSfixed64(AllFields.AllFieldTypes proto) {
        return proto.getOptionalSfixed64();
    }

    @Override
    protected boolean extractHasOptionalFloat(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalFloat();
    }

    @Override
    protected Float extractOptionalFloat(AllFields.AllFieldTypes proto) {
        return proto.getOptionalFloat();
    }

    @Override
    protected boolean extractHasOptionalDouble(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalDouble();
    }

    @Override
    protected Double extractOptionalDouble(AllFields.AllFieldTypes proto) {
        return proto.getOptionalDouble();
    }

    @Override
    protected boolean extractHasOptionalBool(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalBool();
    }

    @Override
    protected Boolean extractOptionalBool(AllFields.AllFieldTypes proto) {
        return proto.getOptionalBool();
    }

    @Override
    protected boolean extractHasOptionalString(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalString();
    }

    @Override
    protected String extractOptionalString(AllFields.AllFieldTypes proto) {
        return proto.getOptionalString();
    }

    @Override
    protected boolean extractHasOptionalBytes(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalBytes();
    }

    @Override
    protected byte[] extractOptionalBytes(AllFields.AllFieldTypes proto) {
        return proto.getOptionalBytes().toByteArray();
    }

    @Override
    protected boolean extractHasOptionalMessage(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalMessage();
    }

    @Override
    protected NestedMessage extractOptionalMessage(AllFields.AllFieldTypes proto) {
        return new io.alnovis.protowrapper.golden.proto2.wrapper.v2.NestedMessage(proto.getOptionalMessage());
    }

    @Override
    protected boolean extractHasOptionalEnum(AllFields.AllFieldTypes proto) {
        return proto.hasOptionalEnum();
    }

    @Override
    protected TestEnum extractOptionalEnum(AllFields.AllFieldTypes proto) {
        return TestEnum.fromProtoValue(proto.getOptionalEnum().getNumber());
    }

    @Override
    protected List<Integer> extractRepeatedInt32(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedInt32List();
    }

    @Override
    protected List<Long> extractRepeatedInt64(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedInt64List();
    }

    @Override
    protected List<Integer> extractRepeatedUint32(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedUint32List();
    }

    @Override
    protected List<Long> extractRepeatedUint64(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedUint64List();
    }

    @Override
    protected List<Integer> extractRepeatedSint32(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedSint32List();
    }

    @Override
    protected List<Long> extractRepeatedSint64(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedSint64List();
    }

    @Override
    protected List<Integer> extractRepeatedFixed32(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedFixed32List();
    }

    @Override
    protected List<Long> extractRepeatedFixed64(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedFixed64List();
    }

    @Override
    protected List<Integer> extractRepeatedSfixed32(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedSfixed32List();
    }

    @Override
    protected List<Long> extractRepeatedSfixed64(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedSfixed64List();
    }

    @Override
    protected List<Float> extractRepeatedFloat(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedFloatList();
    }

    @Override
    protected List<Double> extractRepeatedDouble(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedDoubleList();
    }

    @Override
    protected List<Boolean> extractRepeatedBool(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedBoolList();
    }

    @Override
    protected List<String> extractRepeatedString(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedStringList();
    }

    @Override
    protected List<byte[]> extractRepeatedBytes(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedBytesList().stream().map(com.google.protobuf.ByteString::toByteArray).collect(java.util.stream.Collectors.toList());
    }

    @Override
    protected List<NestedMessage> extractRepeatedMessage(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedMessageList().stream().map(io.alnovis.protowrapper.golden.proto2.wrapper.v2.NestedMessage::new).collect(java.util.stream.Collectors.toList());
    }

    @Override
    protected List<TestEnum> extractRepeatedEnum(AllFields.AllFieldTypes proto) {
        return proto.getRepeatedEnumList().stream().map(e -> TestEnum.fromProtoValue(e.getNumber())).collect(java.util.stream.Collectors.toList());
    }

    @Override
    protected Map<String, Integer> extractStringToInt32Map(AllFields.AllFieldTypes proto) {
        return proto.getStringToInt32Map();
    }

    @Override
    protected Map<Integer, String> extractInt32ToStringMap(AllFields.AllFieldTypes proto) {
        return proto.getInt32ToStringMap();
    }

    @Override
    protected Map<String, NestedMessage> extractStringToMessageMap(AllFields.AllFieldTypes proto) {
        Map<String, ?> source = proto.getStringToMessageMap();
        Map<String, NestedMessage> result = new LinkedHashMap<>(source.size());
        source.forEach((k, v) -> result.put(k, new io.alnovis.protowrapper.golden.proto2.wrapper.v2.NestedMessage((io.alnovis.protowrapper.golden.proto2.v2.AllFields.NestedMessage) v)));
        return result;
    }

    @Override
    protected Map<String, TestEnum> extractStringToEnumMap(AllFields.AllFieldTypes proto) {
        Map<String, ?> source = proto.getStringToEnumMap();
        Map<String, TestEnum> result = new LinkedHashMap<>(source.size());
        source.forEach((k, v) -> result.put(k, io.alnovis.protowrapper.golden.proto2.wrapper.api.TestEnum.fromProtoValue(((ProtocolMessageEnum) v).getNumber())));
        return result;
    }

    @Override
    protected Map<Long, String> extractInt64ToStringMap(AllFields.AllFieldTypes proto) {
        return proto.getInt64ToStringMap();
    }

    @Override
    protected byte[] serializeToBytes(AllFields.AllFieldTypes proto) {
        return proto.toByteArray();
    }

    @Override
    protected String extractWrapperVersionId(AllFields.AllFieldTypes proto) {
        return ProtocolVersions.V2;
    }

    public static AllFieldTypes from(AllFields.AllFieldTypes proto) {
        return new AllFieldTypes(proto);
    }

    /**
     * Get the underlying typed proto message.
     * @return AllFields.AllFieldTypes
     */
    @Override
    public AllFields.AllFieldTypes getTypedProto() {
        return proto;
    }

    @Override
    protected VersionContext getVersionContext() {
        return VersionContextV2.INSTANCE;
    }

    @Override
    protected io.alnovis.protowrapper.golden.proto2.wrapper.api.AllFieldTypes.Builder createBuilder(
            ) {
        return new BuilderImpl(proto.toBuilder());
    }

    @Override
    protected io.alnovis.protowrapper.golden.proto2.wrapper.api.AllFieldTypes.Builder createEmptyBuilder(
            ) {
        return new BuilderImpl(AllFields.AllFieldTypes.newBuilder());
    }

    public static io.alnovis.protowrapper.golden.proto2.wrapper.api.AllFieldTypes.Builder newBuilder(
            ) {
        return new BuilderImpl(AllFields.AllFieldTypes.newBuilder());
    }

    private static class BuilderImpl extends AbstractAllFieldTypes.AbstractBuilder<AllFields.AllFieldTypes> {
        private final AllFields.AllFieldTypes.Builder protoBuilder;

        BuilderImpl(AllFields.AllFieldTypes.Builder protoBuilder) {
            this.protoBuilder = protoBuilder;
        }

        @Override
        protected String getVersionId() {
            return ProtocolVersions.V2;
        }

        @Override
        protected void doSetRequiredInt32(int requiredInt32) {
            protoBuilder.setRequiredInt32(requiredInt32);
        }

        @Override
        protected void doClearRequiredInt32() {
            protoBuilder.clearRequiredInt32();
        }

        @Override
        protected void doSetRequiredInt64(long requiredInt64) {
            protoBuilder.setRequiredInt64(requiredInt64);
        }

        @Override
        protected void doClearRequiredInt64() {
            protoBuilder.clearRequiredInt64();
        }

        @Override
        protected void doSetRequiredUint32(int requiredUint32) {
            protoBuilder.setRequiredUint32(requiredUint32);
        }

        @Override
        protected void doClearRequiredUint32() {
            protoBuilder.clearRequiredUint32();
        }

        @Override
        protected void doSetRequiredUint64(long requiredUint64) {
            protoBuilder.setRequiredUint64(requiredUint64);
        }

        @Override
        protected void doClearRequiredUint64() {
            protoBuilder.clearRequiredUint64();
        }

        @Override
        protected void doSetRequiredSint32(int requiredSint32) {
            protoBuilder.setRequiredSint32(requiredSint32);
        }

        @Override
        protected void doClearRequiredSint32() {
            protoBuilder.clearRequiredSint32();
        }

        @Override
        protected void doSetRequiredSint64(long requiredSint64) {
            protoBuilder.setRequiredSint64(requiredSint64);
        }

        @Override
        protected void doClearRequiredSint64() {
            protoBuilder.clearRequiredSint64();
        }

        @Override
        protected void doSetRequiredFixed32(int requiredFixed32) {
            protoBuilder.setRequiredFixed32(requiredFixed32);
        }

        @Override
        protected void doClearRequiredFixed32() {
            protoBuilder.clearRequiredFixed32();
        }

        @Override
        protected void doSetRequiredFixed64(long requiredFixed64) {
            protoBuilder.setRequiredFixed64(requiredFixed64);
        }

        @Override
        protected void doClearRequiredFixed64() {
            protoBuilder.clearRequiredFixed64();
        }

        @Override
        protected void doSetRequiredSfixed32(int requiredSfixed32) {
            protoBuilder.setRequiredSfixed32(requiredSfixed32);
        }

        @Override
        protected void doClearRequiredSfixed32() {
            protoBuilder.clearRequiredSfixed32();
        }

        @Override
        protected void doSetRequiredSfixed64(long requiredSfixed64) {
            protoBuilder.setRequiredSfixed64(requiredSfixed64);
        }

        @Override
        protected void doClearRequiredSfixed64() {
            protoBuilder.clearRequiredSfixed64();
        }

        @Override
        protected void doSetRequiredFloat(float requiredFloat) {
            protoBuilder.setRequiredFloat(requiredFloat);
        }

        @Override
        protected void doClearRequiredFloat() {
            protoBuilder.clearRequiredFloat();
        }

        @Override
        protected void doSetRequiredDouble(double requiredDouble) {
            protoBuilder.setRequiredDouble(requiredDouble);
        }

        @Override
        protected void doClearRequiredDouble() {
            protoBuilder.clearRequiredDouble();
        }

        @Override
        protected void doSetRequiredBool(boolean requiredBool) {
            protoBuilder.setRequiredBool(requiredBool);
        }

        @Override
        protected void doClearRequiredBool() {
            protoBuilder.clearRequiredBool();
        }

        @Override
        protected void doSetRequiredString(String requiredString) {
            protoBuilder.setRequiredString(requiredString);
        }

        @Override
        protected void doClearRequiredString() {
            protoBuilder.clearRequiredString();
        }

        @Override
        protected void doSetRequiredBytes(byte[] requiredBytes) {
            protoBuilder.setRequiredBytes(com.google.protobuf.ByteString.copyFrom(requiredBytes));
        }

        @Override
        protected void doClearRequiredBytes() {
            protoBuilder.clearRequiredBytes();
        }

        @Override
        protected void doSetRequiredMessage(NestedMessage requiredMessage) {
            protoBuilder.setRequiredMessage((io.alnovis.protowrapper.golden.proto2.v2.AllFields.NestedMessage) extractProto(requiredMessage));
        }

        @Override
        protected void doClearRequiredMessage() {
            protoBuilder.clearRequiredMessage();
        }

        @Override
        protected void doSetRequiredEnum(TestEnum requiredEnum) {
            io.alnovis.protowrapper.golden.proto2.v2.AllFields.TestEnum protoEnumValue = io.alnovis.protowrapper.golden.proto2.v2.AllFields.TestEnum.valueOf(requiredEnum.getValue());
            if (protoEnumValue == null) {
                throw new IllegalArgumentException("TestEnum." + requiredEnum.name() + " (value=" + requiredEnum.getValue() + ") is not supported in protocol version " + getVersionId());
            }
            protoBuilder.setRequiredEnum(protoEnumValue);
        }

        @Override
        protected void doClearRequiredEnum() {
            protoBuilder.clearRequiredEnum();
        }

        @Override
        protected void doSetOptionalInt32(Integer optionalInt32) {
            protoBuilder.setOptionalInt32(optionalInt32);
        }

        @Override
        protected void doClearOptionalInt32() {
            protoBuilder.clearOptionalInt32();
        }

        @Override
        protected void doSetOptionalInt64(Long optionalInt64) {
            protoBuilder.setOptionalInt64(optionalInt64);
        }

        @Override
        protected void doClearOptionalInt64() {
            protoBuilder.clearOptionalInt64();
        }

        @Override
        protected void doSetOptionalUint32(Integer optionalUint32) {
            protoBuilder.setOptionalUint32(optionalUint32);
        }

        @Override
        protected void doClearOptionalUint32() {
            protoBuilder.clearOptionalUint32();
        }

        @Override
        protected void doSetOptionalUint64(Long optionalUint64) {
            protoBuilder.setOptionalUint64(optionalUint64);
        }

        @Override
        protected void doClearOptionalUint64() {
            protoBuilder.clearOptionalUint64();
        }

        @Override
        protected void doSetOptionalSint32(Integer optionalSint32) {
            protoBuilder.setOptionalSint32(optionalSint32);
        }

        @Override
        protected void doClearOptionalSint32() {
            protoBuilder.clearOptionalSint32();
        }

        @Override
        protected void doSetOptionalSint64(Long optionalSint64) {
            protoBuilder.setOptionalSint64(optionalSint64);
        }

        @Override
        protected void doClearOptionalSint64() {
            protoBuilder.clearOptionalSint64();
        }

        @Override
        protected void doSetOptionalFixed32(Integer optionalFixed32) {
            protoBuilder.setOptionalFixed32(optionalFixed32);
        }

        @Override
        protected void doClearOptionalFixed32() {
            protoBuilder.clearOptionalFixed32();
        }

        @Override
        protected void doSetOptionalFixed64(Long optionalFixed64) {
            protoBuilder.setOptionalFixed64(optionalFixed64);
        }

        @Override
        protected void doClearOptionalFixed64() {
            protoBuilder.clearOptionalFixed64();
        }

        @Override
        protected void doSetOptionalSfixed32(Integer optionalSfixed32) {
            protoBuilder.setOptionalSfixed32(optionalSfixed32);
        }

        @Override
        protected void doClearOptionalSfixed32() {
            protoBuilder.clearOptionalSfixed32();
        }

        @Override
        protected void doSetOptionalSfixed64(Long optionalSfixed64) {
            protoBuilder.setOptionalSfixed64(optionalSfixed64);
        }

        @Override
        protected void doClearOptionalSfixed64() {
            protoBuilder.clearOptionalSfixed64();
        }

        @Override
        protected void doSetOptionalFloat(Float optionalFloat) {
            protoBuilder.setOptionalFloat(optionalFloat);
        }

        @Override
        protected void doClearOptionalFloat() {
            protoBuilder.clearOptionalFloat();
        }

        @Override
        protected void doSetOptionalDouble(Double optionalDouble) {
            protoBuilder.setOptionalDouble(optionalDouble);
        }

        @Override
        protected void doClearOptionalDouble() {
            protoBuilder.clearOptionalDouble();
        }

        @Override
        protected void doSetOptionalBool(Boolean optionalBool) {
            protoBuilder.setOptionalBool(optionalBool);
        }

        @Override
        protected void doClearOptionalBool() {
            protoBuilder.clearOptionalBool();
        }

        @Override
        protected void doSetOptionalString(String optionalString) {
            protoBuilder.setOptionalString(optionalString);
        }

        @Override
        protected void doClearOptionalString() {
            protoBuilder.clearOptionalString();
        }

        @Override
        protected void doSetOptionalBytes(byte[] optionalBytes) {
            protoBuilder.setOptionalBytes(com.google.protobuf.ByteString.copyFrom(optionalBytes));
        }

        @Override
        protected void doClearOptionalBytes() {
            protoBuilder.clearOptionalBytes();
        }

        @Override
        protected void doSetOptionalMessage(NestedMessage optionalMessage) {
            protoBuilder.setOptionalMessage((io.alnovis.protowrapper.golden.proto2.v2.AllFields.NestedMessage) extractProto(optionalMessage));
        }

        @Override
        protected void doClearOptionalMessage() {
            protoBuilder.clearOptionalMessage();
        }

        @Override
        protected void doSetOptionalEnum(TestEnum optionalEnum) {
            io.alnovis.protowrapper.golden.proto2.v2.AllFields.TestEnum protoEnumValue = io.alnovis.protowrapper.golden.proto2.v2.AllFields.TestEnum.valueOf(optionalEnum.getValue());
            if (protoEnumValue == null) {
                throw new IllegalArgumentException("TestEnum." + optionalEnum.name() + " (value=" + optionalEnum.getValue() + ") is not supported in protocol version " + getVersionId());
            }
            protoBuilder.setOptionalEnum(protoEnumValue);
        }

        @Override
        protected void doClearOptionalEnum() {
            protoBuilder.clearOptionalEnum();
        }

        @Override
        protected void doAddRepeatedInt32(Integer repeatedInt32) {
            protoBuilder.addRepeatedInt32(repeatedInt32);
        }

        @Override
        protected void doAddAllRepeatedInt32(List<Integer> repeatedInt32) {
            protoBuilder.addAllRepeatedInt32(repeatedInt32);
        }

        @Override
        protected void doSetRepeatedInt32(List<Integer> repeatedInt32) {
            protoBuilder.clearRepeatedInt32();
            protoBuilder.addAllRepeatedInt32(repeatedInt32);
        }

        @Override
        protected void doClearRepeatedInt32() {
            protoBuilder.clearRepeatedInt32();
        }

        @Override
        protected void doAddRepeatedInt64(Long repeatedInt64) {
            protoBuilder.addRepeatedInt64(repeatedInt64);
        }

        @Override
        protected void doAddAllRepeatedInt64(List<Long> repeatedInt64) {
            protoBuilder.addAllRepeatedInt64(repeatedInt64);
        }

        @Override
        protected void doSetRepeatedInt64(List<Long> repeatedInt64) {
            protoBuilder.clearRepeatedInt64();
            protoBuilder.addAllRepeatedInt64(repeatedInt64);
        }

        @Override
        protected void doClearRepeatedInt64() {
            protoBuilder.clearRepeatedInt64();
        }

        @Override
        protected void doAddRepeatedUint32(Integer repeatedUint32) {
            protoBuilder.addRepeatedUint32(repeatedUint32);
        }

        @Override
        protected void doAddAllRepeatedUint32(List<Integer> repeatedUint32) {
            protoBuilder.addAllRepeatedUint32(repeatedUint32);
        }

        @Override
        protected void doSetRepeatedUint32(List<Integer> repeatedUint32) {
            protoBuilder.clearRepeatedUint32();
            protoBuilder.addAllRepeatedUint32(repeatedUint32);
        }

        @Override
        protected void doClearRepeatedUint32() {
            protoBuilder.clearRepeatedUint32();
        }

        @Override
        protected void doAddRepeatedUint64(Long repeatedUint64) {
            protoBuilder.addRepeatedUint64(repeatedUint64);
        }

        @Override
        protected void doAddAllRepeatedUint64(List<Long> repeatedUint64) {
            protoBuilder.addAllRepeatedUint64(repeatedUint64);
        }

        @Override
        protected void doSetRepeatedUint64(List<Long> repeatedUint64) {
            protoBuilder.clearRepeatedUint64();
            protoBuilder.addAllRepeatedUint64(repeatedUint64);
        }

        @Override
        protected void doClearRepeatedUint64() {
            protoBuilder.clearRepeatedUint64();
        }

        @Override
        protected void doAddRepeatedSint32(Integer repeatedSint32) {
            protoBuilder.addRepeatedSint32(repeatedSint32);
        }

        @Override
        protected void doAddAllRepeatedSint32(List<Integer> repeatedSint32) {
            protoBuilder.addAllRepeatedSint32(repeatedSint32);
        }

        @Override
        protected void doSetRepeatedSint32(List<Integer> repeatedSint32) {
            protoBuilder.clearRepeatedSint32();
            protoBuilder.addAllRepeatedSint32(repeatedSint32);
        }

        @Override
        protected void doClearRepeatedSint32() {
            protoBuilder.clearRepeatedSint32();
        }

        @Override
        protected void doAddRepeatedSint64(Long repeatedSint64) {
            protoBuilder.addRepeatedSint64(repeatedSint64);
        }

        @Override
        protected void doAddAllRepeatedSint64(List<Long> repeatedSint64) {
            protoBuilder.addAllRepeatedSint64(repeatedSint64);
        }

        @Override
        protected void doSetRepeatedSint64(List<Long> repeatedSint64) {
            protoBuilder.clearRepeatedSint64();
            protoBuilder.addAllRepeatedSint64(repeatedSint64);
        }

        @Override
        protected void doClearRepeatedSint64() {
            protoBuilder.clearRepeatedSint64();
        }

        @Override
        protected void doAddRepeatedFixed32(Integer repeatedFixed32) {
            protoBuilder.addRepeatedFixed32(repeatedFixed32);
        }

        @Override
        protected void doAddAllRepeatedFixed32(List<Integer> repeatedFixed32) {
            protoBuilder.addAllRepeatedFixed32(repeatedFixed32);
        }

        @Override
        protected void doSetRepeatedFixed32(List<Integer> repeatedFixed32) {
            protoBuilder.clearRepeatedFixed32();
            protoBuilder.addAllRepeatedFixed32(repeatedFixed32);
        }

        @Override
        protected void doClearRepeatedFixed32() {
            protoBuilder.clearRepeatedFixed32();
        }

        @Override
        protected void doAddRepeatedFixed64(Long repeatedFixed64) {
            protoBuilder.addRepeatedFixed64(repeatedFixed64);
        }

        @Override
        protected void doAddAllRepeatedFixed64(List<Long> repeatedFixed64) {
            protoBuilder.addAllRepeatedFixed64(repeatedFixed64);
        }

        @Override
        protected void doSetRepeatedFixed64(List<Long> repeatedFixed64) {
            protoBuilder.clearRepeatedFixed64();
            protoBuilder.addAllRepeatedFixed64(repeatedFixed64);
        }

        @Override
        protected void doClearRepeatedFixed64() {
            protoBuilder.clearRepeatedFixed64();
        }

        @Override
        protected void doAddRepeatedSfixed32(Integer repeatedSfixed32) {
            protoBuilder.addRepeatedSfixed32(repeatedSfixed32);
        }

        @Override
        protected void doAddAllRepeatedSfixed32(List<Integer> repeatedSfixed32) {
            protoBuilder.addAllRepeatedSfixed32(repeatedSfixed32);
        }

        @Override
        protected void doSetRepeatedSfixed32(List<Integer> repeatedSfixed32) {
            protoBuilder.clearRepeatedSfixed32();
            protoBuilder.addAllRepeatedSfixed32(repeatedSfixed32);
        }

        @Override
        protected void doClearRepeatedSfixed32() {
            protoBuilder.clearRepeatedSfixed32();
        }

        @Override
        protected void doAddRepeatedSfixed64(Long repeatedSfixed64) {
            protoBuilder.addRepeatedSfixed64(repeatedSfixed64);
        }

        @Override
        protected void doAddAllRepeatedSfixed64(List<Long> repeatedSfixed64) {
            protoBuilder.addAllRepeatedSfixed64(repeatedSfixed64);
        }

        @Override
        protected void doSetRepeatedSfixed64(List<Long> repeatedSfixed64) {
            protoBuilder.clearRepeatedSfixed64();
            protoBuilder.addAllRepeatedSfixed64(repeatedSfixed64);
        }

        @Override
        protected void doClearRepeatedSfixed64() {
            protoBuilder.clearRepeatedSfixed64();
        }

        @Override
        protected void doAddRepeatedFloat(Float repeatedFloat) {
            protoBuilder.addRepeatedFloat(repeatedFloat);
        }

        @Override
        protected void doAddAllRepeatedFloat(List<Float> repeatedFloat) {
            protoBuilder.addAllRepeatedFloat(repeatedFloat);
        }

        @Override
        protected void doSetRepeatedFloat(List<Float> repeatedFloat) {
            protoBuilder.clearRepeatedFloat();
            protoBuilder.addAllRepeatedFloat(repeatedFloat);
        }

        @Override
        protected void doClearRepeatedFloat() {
            protoBuilder.clearRepeatedFloat();
        }

        @Override
        protected void doAddRepeatedDouble(Double repeatedDouble) {
            protoBuilder.addRepeatedDouble(repeatedDouble);
        }

        @Override
        protected void doAddAllRepeatedDouble(List<Double> repeatedDouble) {
            protoBuilder.addAllRepeatedDouble(repeatedDouble);
        }

        @Override
        protected void doSetRepeatedDouble(List<Double> repeatedDouble) {
            protoBuilder.clearRepeatedDouble();
            protoBuilder.addAllRepeatedDouble(repeatedDouble);
        }

        @Override
        protected void doClearRepeatedDouble() {
            protoBuilder.clearRepeatedDouble();
        }

        @Override
        protected void doAddRepeatedBool(Boolean repeatedBool) {
            protoBuilder.addRepeatedBool(repeatedBool);
        }

        @Override
        protected void doAddAllRepeatedBool(List<Boolean> repeatedBool) {
            protoBuilder.addAllRepeatedBool(repeatedBool);
        }

        @Override
        protected void doSetRepeatedBool(List<Boolean> repeatedBool) {
            protoBuilder.clearRepeatedBool();
            protoBuilder.addAllRepeatedBool(repeatedBool);
        }

        @Override
        protected void doClearRepeatedBool() {
            protoBuilder.clearRepeatedBool();
        }

        @Override
        protected void doAddRepeatedString(String repeatedString) {
            protoBuilder.addRepeatedString(repeatedString);
        }

        @Override
        protected void doAddAllRepeatedString(List<String> repeatedString) {
            protoBuilder.addAllRepeatedString(repeatedString);
        }

        @Override
        protected void doSetRepeatedString(List<String> repeatedString) {
            protoBuilder.clearRepeatedString();
            protoBuilder.addAllRepeatedString(repeatedString);
        }

        @Override
        protected void doClearRepeatedString() {
            protoBuilder.clearRepeatedString();
        }

        @Override
        protected void doAddRepeatedBytes(byte[] repeatedBytes) {
            protoBuilder.addRepeatedBytes(ByteString.copyFrom(repeatedBytes));
        }

        @Override
        protected void doAddAllRepeatedBytes(List<byte[]> repeatedBytes) {
            repeatedBytes.forEach(e -> protoBuilder.addRepeatedBytes(ByteString.copyFrom(e)));
        }

        @Override
        protected void doSetRepeatedBytes(List<byte[]> repeatedBytes) {
            protoBuilder.clearRepeatedBytes();
            repeatedBytes.forEach(e -> protoBuilder.addRepeatedBytes(ByteString.copyFrom(e)));
        }

        @Override
        protected void doClearRepeatedBytes() {
            protoBuilder.clearRepeatedBytes();
        }

        @Override
        protected void doAddRepeatedMessage(NestedMessage repeatedMessage) {
            protoBuilder.addRepeatedMessage((io.alnovis.protowrapper.golden.proto2.v2.AllFields.NestedMessage) extractProto(repeatedMessage));
        }

        @Override
        protected void doAddAllRepeatedMessage(List<NestedMessage> repeatedMessage) {
            repeatedMessage.forEach(e -> protoBuilder.addRepeatedMessage((io.alnovis.protowrapper.golden.proto2.v2.AllFields.NestedMessage) extractProto(e)));
        }

        @Override
        protected void doSetRepeatedMessage(List<NestedMessage> repeatedMessage) {
            protoBuilder.clearRepeatedMessage();
            repeatedMessage.forEach(e -> protoBuilder.addRepeatedMessage((io.alnovis.protowrapper.golden.proto2.v2.AllFields.NestedMessage) extractProto(e)));
        }

        @Override
        protected void doClearRepeatedMessage() {
            protoBuilder.clearRepeatedMessage();
        }

        @Override
        protected void doAddRepeatedEnum(TestEnum repeatedEnum) {
            protoBuilder.addRepeatedEnum(io.alnovis.protowrapper.golden.proto2.v2.AllFields.TestEnum.valueOf(repeatedEnum.getValue()));
        }

        @Override
        protected void doAddAllRepeatedEnum(List<TestEnum> repeatedEnum) {
            repeatedEnum.forEach(e -> protoBuilder.addRepeatedEnum(io.alnovis.protowrapper.golden.proto2.v2.AllFields.TestEnum.valueOf(e.getValue())));
        }

        @Override
        protected void doSetRepeatedEnum(List<TestEnum> repeatedEnum) {
            protoBuilder.clearRepeatedEnum();
            repeatedEnum.forEach(e -> protoBuilder.addRepeatedEnum(io.alnovis.protowrapper.golden.proto2.v2.AllFields.TestEnum.valueOf(e.getValue())));
        }

        @Override
        protected void doClearRepeatedEnum() {
            protoBuilder.clearRepeatedEnum();
        }

        @Override
        protected void doPutStringToInt32(String key, int value) {
            protoBuilder.putStringToInt32(key, value);
        }

        @Override
        protected void doPutAllStringToInt32(Map<String, Integer> values) {
            protoBuilder.putAllStringToInt32(values);
        }

        @Override
        protected void doRemoveStringToInt32(String key) {
            protoBuilder.removeStringToInt32(key);
        }

        @Override
        protected void doClearStringToInt32() {
            protoBuilder.clearStringToInt32();
        }

        @Override
        protected Map<String, Integer> doGetStringToInt32Map() {
            return protoBuilder.getStringToInt32Map();
        }

        @Override
        protected void doPutInt32ToString(int key, String value) {
            protoBuilder.putInt32ToString(key, value);
        }

        @Override
        protected void doPutAllInt32ToString(Map<Integer, String> values) {
            protoBuilder.putAllInt32ToString(values);
        }

        @Override
        protected void doRemoveInt32ToString(int key) {
            protoBuilder.removeInt32ToString(key);
        }

        @Override
        protected void doClearInt32ToString() {
            protoBuilder.clearInt32ToString();
        }

        @Override
        protected Map<Integer, String> doGetInt32ToStringMap() {
            return protoBuilder.getInt32ToStringMap();
        }

        @Override
        protected void doPutStringToMessage(String key, NestedMessage value) {
            protoBuilder.putStringToMessage(key, (io.alnovis.protowrapper.golden.proto2.v2.AllFields.NestedMessage) extractProto(value));
        }

        @Override
        protected void doPutAllStringToMessage(Map<String, NestedMessage> values) {
            values.forEach((k, v) -> doPutStringToMessage(k, v));
        }

        @Override
        protected void doRemoveStringToMessage(String key) {
            protoBuilder.removeStringToMessage(key);
        }

        @Override
        protected void doClearStringToMessage() {
            protoBuilder.clearStringToMessage();
        }

        @Override
        protected Map<String, NestedMessage> doGetStringToMessageMap() {
            Map<String, ?> source = protoBuilder.getStringToMessageMap();
            Map<String, NestedMessage> result = new LinkedHashMap<>(source.size());
            source.forEach((k, v) -> result.put(k, new io.alnovis.protowrapper.golden.proto2.wrapper.v2.NestedMessage((io.alnovis.protowrapper.golden.proto2.v2.AllFields.NestedMessage) v)));
            return result;
        }

        @Override
        protected void doPutStringToEnum(String key, TestEnum value) {
            protoBuilder.putStringToEnum(key, io.alnovis.protowrapper.golden.proto2.v2.AllFields.TestEnum.valueOf(value.getValue()));
        }

        @Override
        protected void doPutAllStringToEnum(Map<String, TestEnum> values) {
            values.forEach((k, v) -> doPutStringToEnum(k, v));
        }

        @Override
        protected void doRemoveStringToEnum(String key) {
            protoBuilder.removeStringToEnum(key);
        }

        @Override
        protected void doClearStringToEnum() {
            protoBuilder.clearStringToEnum();
        }

        @Override
        protected Map<String, TestEnum> doGetStringToEnumMap() {
            Map<String, ?> source = protoBuilder.getStringToEnumMap();
            Map<String, TestEnum> result = new LinkedHashMap<>(source.size());
            source.forEach((k, v) -> result.put(k, io.alnovis.protowrapper.golden.proto2.wrapper.api.TestEnum.fromProtoValue(((ProtocolMessageEnum) v).getNumber())));
            return result;
        }

        @Override
        protected void doPutInt64ToString(long key, String value) {
            protoBuilder.putInt64ToString(key, value);
        }

        @Override
        protected void doPutAllInt64ToString(Map<Long, String> values) {
            protoBuilder.putAllInt64ToString(values);
        }

        @Override
        protected void doRemoveInt64ToString(long key) {
            protoBuilder.removeInt64ToString(key);
        }

        @Override
        protected void doClearInt64ToString() {
            protoBuilder.clearInt64ToString();
        }

        @Override
        protected Map<Long, String> doGetInt64ToStringMap() {
            return protoBuilder.getInt64ToStringMap();
        }

        @Override
        protected io.alnovis.protowrapper.golden.proto2.wrapper.api.AllFieldTypes doBuild() {
            return new AllFieldTypes(protoBuilder.build());
        }

        private Message extractProto(Object wrapper) {
            if (wrapper == null) {
                return null;
            }
            try {
                Method method = wrapper.getClass().getMethod("getTypedProto");
                return (Message) method.invoke(wrapper);
            } catch (Exception e) {
                throw new RuntimeException("Cannot extract proto from " + wrapper.getClass(), e);
            }
        }
    }
}
