package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Example Spring Boot application demonstrating proto-wrapper-spring-boot-starter.
 *
 * <p>This application shows how to use version-agnostic wrappers generated by
 * proto-wrapper plugin with automatic request-scoped version context.
 *
 * <p>Usage:
 * <pre>
 * # Start the application
 * mvn spring-boot:run
 *
 * # Create order using v1 protocol
 * curl -X POST http://localhost:8080/api/orders \
 *   -H "Content-Type: application/json" \
 *   -H "X-Protocol-Version: v1" \
 *   -d '{"customerName": "John", "items": [{"productId": "P1", "name": "Widget", "quantity": 2, "price": 9.99}]}'
 *
 * # Create order using v2 protocol (with shipping address)
 * curl -X POST http://localhost:8080/api/orders \
 *   -H "Content-Type: application/json" \
 *   -H "X-Protocol-Version: v2" \
 *   -d '{"customerName": "John", "items": [...], "shippingAddress": {"street": "123 Main St", ...}}'
 * </pre>
 */
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
}
