// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto2.wrapper.v1;

import io.alnovis.protowrapper.golden.proto2.v1.AllFields;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.ProtocolVersions;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.VersionContext;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.impl.AbstractNestedMessage;
import java.lang.Override;
import java.lang.String;

/**
 * V1 implementation of NestedMessage interface.
 *
 * @see AbstractNestedMessage
 */
public class NestedMessage extends AbstractNestedMessage<AllFields.NestedMessage> {
    public NestedMessage(AllFields.NestedMessage proto) {
        super(proto);
    }

    @Override
    protected boolean extractHasId(AllFields.NestedMessage proto) {
        return proto.hasId();
    }

    @Override
    protected int extractId(AllFields.NestedMessage proto) {
        return proto.getId();
    }

    @Override
    protected boolean extractHasName(AllFields.NestedMessage proto) {
        return proto.hasName();
    }

    @Override
    protected String extractName(AllFields.NestedMessage proto) {
        return proto.getName();
    }

    @Override
    protected byte[] serializeToBytes(AllFields.NestedMessage proto) {
        return proto.toByteArray();
    }

    @Override
    protected String extractWrapperVersionId(AllFields.NestedMessage proto) {
        return ProtocolVersions.V1;
    }

    public static NestedMessage from(AllFields.NestedMessage proto) {
        return new NestedMessage(proto);
    }

    /**
     * Get the underlying typed proto message.
     * @return AllFields.NestedMessage
     */
    @Override
    public AllFields.NestedMessage getTypedProto() {
        return proto;
    }

    @Override
    protected VersionContext getVersionContext() {
        return VersionContextV1.INSTANCE;
    }

    @Override
    protected io.alnovis.protowrapper.golden.proto2.wrapper.api.NestedMessage.Builder createBuilder(
            ) {
        return new BuilderImpl(proto.toBuilder());
    }

    @Override
    protected io.alnovis.protowrapper.golden.proto2.wrapper.api.NestedMessage.Builder createEmptyBuilder(
            ) {
        return new BuilderImpl(AllFields.NestedMessage.newBuilder());
    }

    public static io.alnovis.protowrapper.golden.proto2.wrapper.api.NestedMessage.Builder newBuilder(
            ) {
        return new BuilderImpl(AllFields.NestedMessage.newBuilder());
    }

    private static class BuilderImpl extends AbstractNestedMessage.AbstractBuilder<AllFields.NestedMessage> {
        private final AllFields.NestedMessage.Builder protoBuilder;

        BuilderImpl(AllFields.NestedMessage.Builder protoBuilder) {
            this.protoBuilder = protoBuilder;
        }

        @Override
        protected String getVersionId() {
            return ProtocolVersions.V1;
        }

        @Override
        protected void doSetId(int id) {
            protoBuilder.setId(id);
        }

        @Override
        protected void doClearId() {
            protoBuilder.clearId();
        }

        @Override
        protected void doSetName(String name) {
            protoBuilder.setName(name);
        }

        @Override
        protected void doClearName() {
            protoBuilder.clearName();
        }

        @Override
        protected io.alnovis.protowrapper.golden.proto2.wrapper.api.NestedMessage doBuild() {
            return new NestedMessage(protoBuilder.build());
        }
    }
}
