// Generated by proto-wrapper-maven-plugin. DO NOT EDIT.
package io.alnovis.protowrapper.golden.proto2.wrapper.api.impl;

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.Message;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.AllFieldTypes;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.NestedMessage;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.TestEnum;
import io.alnovis.protowrapper.golden.proto2.wrapper.api.VersionContext;
import java.lang.Boolean;
import java.lang.Class;
import java.lang.Double;
import java.lang.Exception;
import java.lang.Float;
import java.lang.IllegalArgumentException;
import java.lang.IllegalStateException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.NumberFormatException;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.Throwable;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Abstract base class for AllFieldTypes implementations.
 *
 * <p>Uses template method pattern - subclasses implement extract* methods.</p>
 * @param <PROTO> Protocol-specific message type
 */
public abstract class AbstractAllFieldTypes<PROTO extends Message> implements AllFieldTypes {
    /**
     * The underlying proto message.
     */
    protected final PROTO proto;

    protected AbstractAllFieldTypes(PROTO proto) {
        this.proto = proto;
    }

    protected abstract boolean extractHasRequiredInt32(PROTO proto);

    protected abstract int extractRequiredInt32(PROTO proto);

    protected abstract boolean extractHasRequiredInt64(PROTO proto);

    protected abstract long extractRequiredInt64(PROTO proto);

    protected abstract boolean extractHasRequiredUint32(PROTO proto);

    protected abstract int extractRequiredUint32(PROTO proto);

    protected abstract boolean extractHasRequiredUint64(PROTO proto);

    protected abstract long extractRequiredUint64(PROTO proto);

    protected abstract boolean extractHasRequiredSint32(PROTO proto);

    protected abstract int extractRequiredSint32(PROTO proto);

    protected abstract boolean extractHasRequiredSint64(PROTO proto);

    protected abstract long extractRequiredSint64(PROTO proto);

    protected abstract boolean extractHasRequiredFixed32(PROTO proto);

    protected abstract int extractRequiredFixed32(PROTO proto);

    protected abstract boolean extractHasRequiredFixed64(PROTO proto);

    protected abstract long extractRequiredFixed64(PROTO proto);

    protected abstract boolean extractHasRequiredSfixed32(PROTO proto);

    protected abstract int extractRequiredSfixed32(PROTO proto);

    protected abstract boolean extractHasRequiredSfixed64(PROTO proto);

    protected abstract long extractRequiredSfixed64(PROTO proto);

    protected abstract boolean extractHasRequiredFloat(PROTO proto);

    protected abstract float extractRequiredFloat(PROTO proto);

    protected abstract boolean extractHasRequiredDouble(PROTO proto);

    protected abstract double extractRequiredDouble(PROTO proto);

    protected abstract boolean extractHasRequiredBool(PROTO proto);

    protected abstract boolean extractRequiredBool(PROTO proto);

    protected abstract boolean extractHasRequiredString(PROTO proto);

    protected abstract String extractRequiredString(PROTO proto);

    protected abstract boolean extractHasRequiredBytes(PROTO proto);

    protected abstract byte[] extractRequiredBytes(PROTO proto);

    protected abstract boolean extractHasRequiredMessage(PROTO proto);

    protected abstract NestedMessage extractRequiredMessage(PROTO proto);

    protected abstract boolean extractHasRequiredEnum(PROTO proto);

    protected abstract TestEnum extractRequiredEnum(PROTO proto);

    protected abstract boolean extractHasOptionalInt32(PROTO proto);

    protected abstract Integer extractOptionalInt32(PROTO proto);

    protected abstract boolean extractHasOptionalInt64(PROTO proto);

    protected abstract Long extractOptionalInt64(PROTO proto);

    protected abstract boolean extractHasOptionalUint32(PROTO proto);

    protected abstract Integer extractOptionalUint32(PROTO proto);

    protected abstract boolean extractHasOptionalUint64(PROTO proto);

    protected abstract Long extractOptionalUint64(PROTO proto);

    protected abstract boolean extractHasOptionalSint32(PROTO proto);

    protected abstract Integer extractOptionalSint32(PROTO proto);

    protected abstract boolean extractHasOptionalSint64(PROTO proto);

    protected abstract Long extractOptionalSint64(PROTO proto);

    protected abstract boolean extractHasOptionalFixed32(PROTO proto);

    protected abstract Integer extractOptionalFixed32(PROTO proto);

    protected abstract boolean extractHasOptionalFixed64(PROTO proto);

    protected abstract Long extractOptionalFixed64(PROTO proto);

    protected abstract boolean extractHasOptionalSfixed32(PROTO proto);

    protected abstract Integer extractOptionalSfixed32(PROTO proto);

    protected abstract boolean extractHasOptionalSfixed64(PROTO proto);

    protected abstract Long extractOptionalSfixed64(PROTO proto);

    protected abstract boolean extractHasOptionalFloat(PROTO proto);

    protected abstract Float extractOptionalFloat(PROTO proto);

    protected abstract boolean extractHasOptionalDouble(PROTO proto);

    protected abstract Double extractOptionalDouble(PROTO proto);

    protected abstract boolean extractHasOptionalBool(PROTO proto);

    protected abstract Boolean extractOptionalBool(PROTO proto);

    protected abstract boolean extractHasOptionalString(PROTO proto);

    protected abstract String extractOptionalString(PROTO proto);

    protected abstract boolean extractHasOptionalBytes(PROTO proto);

    protected abstract byte[] extractOptionalBytes(PROTO proto);

    protected abstract boolean extractHasOptionalMessage(PROTO proto);

    protected abstract NestedMessage extractOptionalMessage(PROTO proto);

    protected abstract boolean extractHasOptionalEnum(PROTO proto);

    protected abstract TestEnum extractOptionalEnum(PROTO proto);

    protected abstract List<Integer> extractRepeatedInt32(PROTO proto);

    protected abstract List<Long> extractRepeatedInt64(PROTO proto);

    protected abstract List<Integer> extractRepeatedUint32(PROTO proto);

    protected abstract List<Long> extractRepeatedUint64(PROTO proto);

    protected abstract List<Integer> extractRepeatedSint32(PROTO proto);

    protected abstract List<Long> extractRepeatedSint64(PROTO proto);

    protected abstract List<Integer> extractRepeatedFixed32(PROTO proto);

    protected abstract List<Long> extractRepeatedFixed64(PROTO proto);

    protected abstract List<Integer> extractRepeatedSfixed32(PROTO proto);

    protected abstract List<Long> extractRepeatedSfixed64(PROTO proto);

    protected abstract List<Float> extractRepeatedFloat(PROTO proto);

    protected abstract List<Double> extractRepeatedDouble(PROTO proto);

    protected abstract List<Boolean> extractRepeatedBool(PROTO proto);

    protected abstract List<String> extractRepeatedString(PROTO proto);

    protected abstract List<byte[]> extractRepeatedBytes(PROTO proto);

    protected abstract List<NestedMessage> extractRepeatedMessage(PROTO proto);

    protected abstract List<TestEnum> extractRepeatedEnum(PROTO proto);

    protected abstract Map<String, Integer> extractStringToInt32Map(PROTO proto);

    protected abstract Map<Integer, String> extractInt32ToStringMap(PROTO proto);

    protected abstract Map<String, NestedMessage> extractStringToMessageMap(PROTO proto);

    protected abstract Map<String, TestEnum> extractStringToEnumMap(PROTO proto);

    protected abstract Map<Long, String> extractInt64ToStringMap(PROTO proto);

    @Override
    public final int getRequiredInt32() {
        return extractRequiredInt32(proto);
    }

    @Override
    public final boolean hasRequiredInt32() {
        return extractHasRequiredInt32(proto);
    }

    @Override
    public final long getRequiredInt64() {
        return extractRequiredInt64(proto);
    }

    @Override
    public final boolean hasRequiredInt64() {
        return extractHasRequiredInt64(proto);
    }

    @Override
    public final int getRequiredUint32() {
        return extractRequiredUint32(proto);
    }

    @Override
    public final boolean hasRequiredUint32() {
        return extractHasRequiredUint32(proto);
    }

    @Override
    public final long getRequiredUint64() {
        return extractRequiredUint64(proto);
    }

    @Override
    public final boolean hasRequiredUint64() {
        return extractHasRequiredUint64(proto);
    }

    @Override
    public final int getRequiredSint32() {
        return extractRequiredSint32(proto);
    }

    @Override
    public final boolean hasRequiredSint32() {
        return extractHasRequiredSint32(proto);
    }

    @Override
    public final long getRequiredSint64() {
        return extractRequiredSint64(proto);
    }

    @Override
    public final boolean hasRequiredSint64() {
        return extractHasRequiredSint64(proto);
    }

    @Override
    public final int getRequiredFixed32() {
        return extractRequiredFixed32(proto);
    }

    @Override
    public final boolean hasRequiredFixed32() {
        return extractHasRequiredFixed32(proto);
    }

    @Override
    public final long getRequiredFixed64() {
        return extractRequiredFixed64(proto);
    }

    @Override
    public final boolean hasRequiredFixed64() {
        return extractHasRequiredFixed64(proto);
    }

    @Override
    public final int getRequiredSfixed32() {
        return extractRequiredSfixed32(proto);
    }

    @Override
    public final boolean hasRequiredSfixed32() {
        return extractHasRequiredSfixed32(proto);
    }

    @Override
    public final long getRequiredSfixed64() {
        return extractRequiredSfixed64(proto);
    }

    @Override
    public final boolean hasRequiredSfixed64() {
        return extractHasRequiredSfixed64(proto);
    }

    @Override
    public final float getRequiredFloat() {
        return extractRequiredFloat(proto);
    }

    @Override
    public final boolean hasRequiredFloat() {
        return extractHasRequiredFloat(proto);
    }

    @Override
    public final double getRequiredDouble() {
        return extractRequiredDouble(proto);
    }

    @Override
    public final boolean hasRequiredDouble() {
        return extractHasRequiredDouble(proto);
    }

    @Override
    public final boolean isRequiredBool() {
        return extractRequiredBool(proto);
    }

    @Override
    public final boolean hasRequiredBool() {
        return extractHasRequiredBool(proto);
    }

    @Override
    public final String getRequiredString() {
        return extractRequiredString(proto);
    }

    @Override
    public final boolean hasRequiredString() {
        return extractHasRequiredString(proto);
    }

    @Override
    public final byte[] getRequiredBytes() {
        return extractRequiredBytes(proto);
    }

    @Override
    public final boolean hasRequiredBytes() {
        return extractHasRequiredBytes(proto);
    }

    @Override
    public final NestedMessage getRequiredMessage() {
        return extractRequiredMessage(proto);
    }

    @Override
    public final boolean hasRequiredMessage() {
        return extractHasRequiredMessage(proto);
    }

    @Override
    public final TestEnum getRequiredEnum() {
        return extractRequiredEnum(proto);
    }

    @Override
    public final boolean hasRequiredEnum() {
        return extractHasRequiredEnum(proto);
    }

    @Override
    public final Integer getOptionalInt32() {
        return extractHasOptionalInt32(proto) ? extractOptionalInt32(proto) : null;
    }

    @Override
    public final boolean hasOptionalInt32() {
        return extractHasOptionalInt32(proto);
    }

    @Override
    public final Long getOptionalInt64() {
        return extractHasOptionalInt64(proto) ? extractOptionalInt64(proto) : null;
    }

    @Override
    public final boolean hasOptionalInt64() {
        return extractHasOptionalInt64(proto);
    }

    @Override
    public final Integer getOptionalUint32() {
        return extractHasOptionalUint32(proto) ? extractOptionalUint32(proto) : null;
    }

    @Override
    public final boolean hasOptionalUint32() {
        return extractHasOptionalUint32(proto);
    }

    @Override
    public final Long getOptionalUint64() {
        return extractHasOptionalUint64(proto) ? extractOptionalUint64(proto) : null;
    }

    @Override
    public final boolean hasOptionalUint64() {
        return extractHasOptionalUint64(proto);
    }

    @Override
    public final Integer getOptionalSint32() {
        return extractHasOptionalSint32(proto) ? extractOptionalSint32(proto) : null;
    }

    @Override
    public final boolean hasOptionalSint32() {
        return extractHasOptionalSint32(proto);
    }

    @Override
    public final Long getOptionalSint64() {
        return extractHasOptionalSint64(proto) ? extractOptionalSint64(proto) : null;
    }

    @Override
    public final boolean hasOptionalSint64() {
        return extractHasOptionalSint64(proto);
    }

    @Override
    public final Integer getOptionalFixed32() {
        return extractHasOptionalFixed32(proto) ? extractOptionalFixed32(proto) : null;
    }

    @Override
    public final boolean hasOptionalFixed32() {
        return extractHasOptionalFixed32(proto);
    }

    @Override
    public final Long getOptionalFixed64() {
        return extractHasOptionalFixed64(proto) ? extractOptionalFixed64(proto) : null;
    }

    @Override
    public final boolean hasOptionalFixed64() {
        return extractHasOptionalFixed64(proto);
    }

    @Override
    public final Integer getOptionalSfixed32() {
        return extractHasOptionalSfixed32(proto) ? extractOptionalSfixed32(proto) : null;
    }

    @Override
    public final boolean hasOptionalSfixed32() {
        return extractHasOptionalSfixed32(proto);
    }

    @Override
    public final Long getOptionalSfixed64() {
        return extractHasOptionalSfixed64(proto) ? extractOptionalSfixed64(proto) : null;
    }

    @Override
    public final boolean hasOptionalSfixed64() {
        return extractHasOptionalSfixed64(proto);
    }

    @Override
    public final Float getOptionalFloat() {
        return extractHasOptionalFloat(proto) ? extractOptionalFloat(proto) : null;
    }

    @Override
    public final boolean hasOptionalFloat() {
        return extractHasOptionalFloat(proto);
    }

    @Override
    public final Double getOptionalDouble() {
        return extractHasOptionalDouble(proto) ? extractOptionalDouble(proto) : null;
    }

    @Override
    public final boolean hasOptionalDouble() {
        return extractHasOptionalDouble(proto);
    }

    @Override
    public final Boolean isOptionalBool() {
        return extractHasOptionalBool(proto) ? extractOptionalBool(proto) : null;
    }

    @Override
    public final boolean hasOptionalBool() {
        return extractHasOptionalBool(proto);
    }

    @Override
    public final String getOptionalString() {
        return extractOptionalString(proto);
    }

    @Override
    public final boolean hasOptionalString() {
        return extractHasOptionalString(proto);
    }

    @Override
    public final byte[] getOptionalBytes() {
        return extractOptionalBytes(proto);
    }

    @Override
    public final boolean hasOptionalBytes() {
        return extractHasOptionalBytes(proto);
    }

    @Override
    public final NestedMessage getOptionalMessage() {
        return extractHasOptionalMessage(proto) ? extractOptionalMessage(proto) : null;
    }

    @Override
    public final boolean hasOptionalMessage() {
        return extractHasOptionalMessage(proto);
    }

    @Override
    public final TestEnum getOptionalEnum() {
        return extractOptionalEnum(proto);
    }

    @Override
    public final boolean hasOptionalEnum() {
        return extractHasOptionalEnum(proto);
    }

    @Override
    public final List<Integer> getRepeatedInt32() {
        return extractRepeatedInt32(proto);
    }

    @Override
    public final List<Long> getRepeatedInt64() {
        return extractRepeatedInt64(proto);
    }

    @Override
    public final List<Integer> getRepeatedUint32() {
        return extractRepeatedUint32(proto);
    }

    @Override
    public final List<Long> getRepeatedUint64() {
        return extractRepeatedUint64(proto);
    }

    @Override
    public final List<Integer> getRepeatedSint32() {
        return extractRepeatedSint32(proto);
    }

    @Override
    public final List<Long> getRepeatedSint64() {
        return extractRepeatedSint64(proto);
    }

    @Override
    public final List<Integer> getRepeatedFixed32() {
        return extractRepeatedFixed32(proto);
    }

    @Override
    public final List<Long> getRepeatedFixed64() {
        return extractRepeatedFixed64(proto);
    }

    @Override
    public final List<Integer> getRepeatedSfixed32() {
        return extractRepeatedSfixed32(proto);
    }

    @Override
    public final List<Long> getRepeatedSfixed64() {
        return extractRepeatedSfixed64(proto);
    }

    @Override
    public final List<Float> getRepeatedFloat() {
        return extractRepeatedFloat(proto);
    }

    @Override
    public final List<Double> getRepeatedDouble() {
        return extractRepeatedDouble(proto);
    }

    @Override
    public final List<Boolean> getRepeatedBool() {
        return extractRepeatedBool(proto);
    }

    @Override
    public final List<String> getRepeatedString() {
        return extractRepeatedString(proto);
    }

    @Override
    public final List<byte[]> getRepeatedBytes() {
        return extractRepeatedBytes(proto);
    }

    @Override
    public final List<NestedMessage> getRepeatedMessage() {
        return extractRepeatedMessage(proto);
    }

    @Override
    public final List<TestEnum> getRepeatedEnum() {
        return extractRepeatedEnum(proto);
    }

    @Override
    public final Map<String, Integer> getStringToInt32Map() {
        return Collections.unmodifiableMap(extractStringToInt32Map(proto));
    }

    @Override
    public final int getStringToInt32Count() {
        return extractStringToInt32Map(proto).size();
    }

    @Override
    public final boolean containsStringToInt32(String key) {
        return extractStringToInt32Map(proto).containsKey(key);
    }

    @Override
    public final int getStringToInt32OrDefault(String key, int defaultValue) {
        Map<String, Integer> map = extractStringToInt32Map(proto);
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    @Override
    public final int getStringToInt32OrThrow(String key) {
        Map<String, Integer> map = extractStringToInt32Map(proto);
        if (!map.containsKey(key)) {
            throw new IllegalArgumentException("Key not found: " + key);
        }
        return map.get(key);
    }

    @Override
    public final Map<Integer, String> getInt32ToStringMap() {
        return Collections.unmodifiableMap(extractInt32ToStringMap(proto));
    }

    @Override
    public final int getInt32ToStringCount() {
        return extractInt32ToStringMap(proto).size();
    }

    @Override
    public final boolean containsInt32ToString(int key) {
        return extractInt32ToStringMap(proto).containsKey(key);
    }

    @Override
    public final String getInt32ToStringOrDefault(int key, String defaultValue) {
        Map<Integer, String> map = extractInt32ToStringMap(proto);
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    @Override
    public final String getInt32ToStringOrThrow(int key) {
        Map<Integer, String> map = extractInt32ToStringMap(proto);
        if (!map.containsKey(key)) {
            throw new IllegalArgumentException("Key not found: " + key);
        }
        return map.get(key);
    }

    @Override
    public final Map<String, NestedMessage> getStringToMessageMap() {
        return Collections.unmodifiableMap(extractStringToMessageMap(proto));
    }

    @Override
    public final int getStringToMessageCount() {
        return extractStringToMessageMap(proto).size();
    }

    @Override
    public final boolean containsStringToMessage(String key) {
        return extractStringToMessageMap(proto).containsKey(key);
    }

    @Override
    public final NestedMessage getStringToMessageOrDefault(String key, NestedMessage defaultValue) {
        Map<String, NestedMessage> map = extractStringToMessageMap(proto);
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    @Override
    public final NestedMessage getStringToMessageOrThrow(String key) {
        Map<String, NestedMessage> map = extractStringToMessageMap(proto);
        if (!map.containsKey(key)) {
            throw new IllegalArgumentException("Key not found: " + key);
        }
        return map.get(key);
    }

    @Override
    public final Map<String, TestEnum> getStringToEnumMap() {
        return Collections.unmodifiableMap(extractStringToEnumMap(proto));
    }

    @Override
    public final int getStringToEnumCount() {
        return extractStringToEnumMap(proto).size();
    }

    @Override
    public final boolean containsStringToEnum(String key) {
        return extractStringToEnumMap(proto).containsKey(key);
    }

    @Override
    public final TestEnum getStringToEnumOrDefault(String key, TestEnum defaultValue) {
        Map<String, TestEnum> map = extractStringToEnumMap(proto);
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    @Override
    public final TestEnum getStringToEnumOrThrow(String key) {
        Map<String, TestEnum> map = extractStringToEnumMap(proto);
        if (!map.containsKey(key)) {
            throw new IllegalArgumentException("Key not found: " + key);
        }
        return map.get(key);
    }

    @Override
    public final Map<Long, String> getInt64ToStringMap() {
        return Collections.unmodifiableMap(extractInt64ToStringMap(proto));
    }

    @Override
    public final int getInt64ToStringCount() {
        return extractInt64ToStringMap(proto).size();
    }

    @Override
    public final boolean containsInt64ToString(long key) {
        return extractInt64ToStringMap(proto).containsKey(key);
    }

    @Override
    public final String getInt64ToStringOrDefault(long key, String defaultValue) {
        Map<Long, String> map = extractInt64ToStringMap(proto);
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    @Override
    public final String getInt64ToStringOrThrow(long key) {
        Map<Long, String> map = extractInt64ToStringMap(proto);
        if (!map.containsKey(key)) {
            throw new IllegalArgumentException("Key not found: " + key);
        }
        return map.get(key);
    }

    /**
     * Get the underlying protobuf message.
     * @return protobuf Message
     */
    @Override
    public Message getTypedProto() {
        return proto;
    }

    protected abstract byte[] serializeToBytes(PROTO proto);

    @Override
    public final byte[] toBytes() {
        return serializeToBytes(proto);
    }

    protected abstract String extractWrapperVersionId(PROTO proto);

    @Override
    public final String getWrapperVersionId() {
        return extractWrapperVersionId(proto);
    }

    @Override
    public <T extends AllFieldTypes> T asVersion(Class<T> versionClass) {
        return convertToVersion(versionClass);
    }

    @Override
    public <T extends AllFieldTypes> T asVersionStrict(Class<T> versionClass) {
        if (versionClass.isInstance(this)) {
            return versionClass.cast(this);
        }
        int targetVersion = extractVersionFromPackage(versionClass.getPackage().getName());
        List<String> inaccessibleFields = getFieldsInaccessibleInVersion(targetVersion);
        if (!inaccessibleFields.isEmpty()) {
            throw new IllegalStateException(String.format("Cannot convert from version %s to version %d: the following fields have values but will become inaccessible in the target version: %s. Use asVersion() if you want to proceed anyway (data is preserved via protobuf unknown fields).", getWrapperVersionId(), targetVersion, inaccessibleFields));
        }
        return convertToVersion(versionClass);
    }

    @Override
    public AllFieldTypes asVersion(VersionContext targetContext) {
        if (targetContext.getVersionId().equals(getWrapperVersionId())) {
            return this;
        }
        try {
            return targetContext.parseAllFieldTypesFromBytes(this.toBytes());
        } catch (InvalidProtocolBufferException e) {
            throw new RuntimeException(String.format("Failed to convert %s from version %s to %s: %s", getClass().getSimpleName(), getWrapperVersionId(), targetContext.getVersionId(), e.getMessage()), e);
        }
    }

    /**
     * Convert to a specific version via serialization.
     * @param versionClass Target version class
     * @return Instance of the specified version
     */
    protected <T extends AllFieldTypes> T convertToVersion(Class<T> versionClass) {
        if (versionClass.isInstance(this)) {
            return versionClass.cast(this);
        }
        String targetVersionId = extractVersionIdFromPackage(versionClass.getPackage().getName());
        try {
            VersionContext targetContext = VersionContext.forVersionId(targetVersionId);
            byte[] bytes = this.toBytes();
            Method parseMethod = targetContext.getClass().getMethod("parseAllFieldTypesFromBytes", byte[].class);
            return versionClass.cast(parseMethod.invoke(targetContext, bytes));
        } catch (InvocationTargetException e) {
            Throwable cause = e.getCause() != null ? e.getCause() : e;
            throw new RuntimeException(String.format("Failed to convert %s from version %s to %s: %s - %s", getClass().getSimpleName(), getWrapperVersionId(), targetVersionId, cause.getClass().getSimpleName(), cause.getMessage()), cause);
        } catch (Exception e) {
            throw new RuntimeException(String.format("Failed to convert %s from version %s to %s: %s", getClass().getSimpleName(), getWrapperVersionId(), targetVersionId, e.getMessage()), e);
        }
    }

    private static String extractVersionIdFromPackage(String packageName) {
        int lastDot = packageName.lastIndexOf('.');
        if (lastDot > 0) {
            String lastSegment = packageName.substring(lastDot + 1);
            if (lastSegment.startsWith("v") && lastSegment.length() > 1) {
                return lastSegment;
            }
            int secondLastDot = packageName.lastIndexOf('.', lastDot - 1);
            if (secondLastDot > 0) {
                String secondLastSegment = packageName.substring(secondLastDot + 1, lastDot);
                if (secondLastSegment.startsWith("v") && secondLastSegment.length() > 1) {
                    return secondLastSegment;
                }
            }
        }
        throw new IllegalArgumentException("Cannot extract version from package: " + packageName);
    }

    private static int extractVersionFromPackage(String packageName) {
        String versionId = extractVersionIdFromPackage(packageName);
        String numStr = versionId.replaceAll("[^0-9]", "");
        try {
            return Integer.parseInt(numStr);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Cannot parse version number from: " + versionId);
        }
    }

    @Override
    public String toString() {
        return String.format("%s[version=%s] %s", getClass().getSimpleName(), getWrapperVersionId(), proto.toString().replace("\n", ", ").trim());
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        AbstractAllFieldTypes<?> other = (AbstractAllFieldTypes<?>) obj;
        return Objects.equals(this.getWrapperVersionId(), other.getWrapperVersionId()) && Objects.equals(this.proto, other.proto);
    }

    @Override
    public int hashCode() {
        return Objects.hash(getWrapperVersionId(), proto);
    }

    protected abstract VersionContext getVersionContext();

    @Override
    public final VersionContext getContext() {
        return getVersionContext();
    }

    @Override
    public List<String> getFieldsInaccessibleInVersion(int targetVersion) {
        List<String> inaccessible = new ArrayList<>();
        return inaccessible;
    }

    protected abstract AllFieldTypes.Builder createBuilder();

    @Override
    public final AllFieldTypes.Builder toBuilder() {
        return createBuilder();
    }

    protected abstract AllFieldTypes.Builder createEmptyBuilder();

    @Override
    public final AllFieldTypes.Builder emptyBuilder() {
        return createEmptyBuilder();
    }

    /**
     * Abstract builder base class.
     * @param <PROTO> Protocol-specific message type
     */
    public abstract static class AbstractBuilder<PROTO extends Message> implements AllFieldTypes.Builder {
        protected abstract void doSetRequiredInt32(int requiredInt32);

        protected abstract void doClearRequiredInt32();

        protected abstract void doSetRequiredInt64(long requiredInt64);

        protected abstract void doClearRequiredInt64();

        protected abstract void doSetRequiredUint32(int requiredUint32);

        protected abstract void doClearRequiredUint32();

        protected abstract void doSetRequiredUint64(long requiredUint64);

        protected abstract void doClearRequiredUint64();

        protected abstract void doSetRequiredSint32(int requiredSint32);

        protected abstract void doClearRequiredSint32();

        protected abstract void doSetRequiredSint64(long requiredSint64);

        protected abstract void doClearRequiredSint64();

        protected abstract void doSetRequiredFixed32(int requiredFixed32);

        protected abstract void doClearRequiredFixed32();

        protected abstract void doSetRequiredFixed64(long requiredFixed64);

        protected abstract void doClearRequiredFixed64();

        protected abstract void doSetRequiredSfixed32(int requiredSfixed32);

        protected abstract void doClearRequiredSfixed32();

        protected abstract void doSetRequiredSfixed64(long requiredSfixed64);

        protected abstract void doClearRequiredSfixed64();

        protected abstract void doSetRequiredFloat(float requiredFloat);

        protected abstract void doClearRequiredFloat();

        protected abstract void doSetRequiredDouble(double requiredDouble);

        protected abstract void doClearRequiredDouble();

        protected abstract void doSetRequiredBool(boolean requiredBool);

        protected abstract void doClearRequiredBool();

        protected abstract void doSetRequiredString(String requiredString);

        protected abstract void doClearRequiredString();

        protected abstract void doSetRequiredBytes(byte[] requiredBytes);

        protected abstract void doClearRequiredBytes();

        protected abstract void doSetRequiredMessage(NestedMessage requiredMessage);

        protected abstract void doClearRequiredMessage();

        protected abstract void doSetRequiredEnum(TestEnum requiredEnum);

        protected abstract void doClearRequiredEnum();

        protected abstract void doSetOptionalInt32(Integer optionalInt32);

        protected abstract void doClearOptionalInt32();

        protected abstract void doSetOptionalInt64(Long optionalInt64);

        protected abstract void doClearOptionalInt64();

        protected abstract void doSetOptionalUint32(Integer optionalUint32);

        protected abstract void doClearOptionalUint32();

        protected abstract void doSetOptionalUint64(Long optionalUint64);

        protected abstract void doClearOptionalUint64();

        protected abstract void doSetOptionalSint32(Integer optionalSint32);

        protected abstract void doClearOptionalSint32();

        protected abstract void doSetOptionalSint64(Long optionalSint64);

        protected abstract void doClearOptionalSint64();

        protected abstract void doSetOptionalFixed32(Integer optionalFixed32);

        protected abstract void doClearOptionalFixed32();

        protected abstract void doSetOptionalFixed64(Long optionalFixed64);

        protected abstract void doClearOptionalFixed64();

        protected abstract void doSetOptionalSfixed32(Integer optionalSfixed32);

        protected abstract void doClearOptionalSfixed32();

        protected abstract void doSetOptionalSfixed64(Long optionalSfixed64);

        protected abstract void doClearOptionalSfixed64();

        protected abstract void doSetOptionalFloat(Float optionalFloat);

        protected abstract void doClearOptionalFloat();

        protected abstract void doSetOptionalDouble(Double optionalDouble);

        protected abstract void doClearOptionalDouble();

        protected abstract void doSetOptionalBool(Boolean optionalBool);

        protected abstract void doClearOptionalBool();

        protected abstract void doSetOptionalString(String optionalString);

        protected abstract void doClearOptionalString();

        protected abstract void doSetOptionalBytes(byte[] optionalBytes);

        protected abstract void doClearOptionalBytes();

        protected abstract void doSetOptionalMessage(NestedMessage optionalMessage);

        protected abstract void doClearOptionalMessage();

        protected abstract void doSetOptionalEnum(TestEnum optionalEnum);

        protected abstract void doClearOptionalEnum();

        protected abstract void doAddRepeatedInt32(Integer repeatedInt32);

        protected abstract void doAddAllRepeatedInt32(List<Integer> repeatedInt32);

        protected abstract void doSetRepeatedInt32(List<Integer> repeatedInt32);

        protected abstract void doClearRepeatedInt32();

        protected abstract void doAddRepeatedInt64(Long repeatedInt64);

        protected abstract void doAddAllRepeatedInt64(List<Long> repeatedInt64);

        protected abstract void doSetRepeatedInt64(List<Long> repeatedInt64);

        protected abstract void doClearRepeatedInt64();

        protected abstract void doAddRepeatedUint32(Integer repeatedUint32);

        protected abstract void doAddAllRepeatedUint32(List<Integer> repeatedUint32);

        protected abstract void doSetRepeatedUint32(List<Integer> repeatedUint32);

        protected abstract void doClearRepeatedUint32();

        protected abstract void doAddRepeatedUint64(Long repeatedUint64);

        protected abstract void doAddAllRepeatedUint64(List<Long> repeatedUint64);

        protected abstract void doSetRepeatedUint64(List<Long> repeatedUint64);

        protected abstract void doClearRepeatedUint64();

        protected abstract void doAddRepeatedSint32(Integer repeatedSint32);

        protected abstract void doAddAllRepeatedSint32(List<Integer> repeatedSint32);

        protected abstract void doSetRepeatedSint32(List<Integer> repeatedSint32);

        protected abstract void doClearRepeatedSint32();

        protected abstract void doAddRepeatedSint64(Long repeatedSint64);

        protected abstract void doAddAllRepeatedSint64(List<Long> repeatedSint64);

        protected abstract void doSetRepeatedSint64(List<Long> repeatedSint64);

        protected abstract void doClearRepeatedSint64();

        protected abstract void doAddRepeatedFixed32(Integer repeatedFixed32);

        protected abstract void doAddAllRepeatedFixed32(List<Integer> repeatedFixed32);

        protected abstract void doSetRepeatedFixed32(List<Integer> repeatedFixed32);

        protected abstract void doClearRepeatedFixed32();

        protected abstract void doAddRepeatedFixed64(Long repeatedFixed64);

        protected abstract void doAddAllRepeatedFixed64(List<Long> repeatedFixed64);

        protected abstract void doSetRepeatedFixed64(List<Long> repeatedFixed64);

        protected abstract void doClearRepeatedFixed64();

        protected abstract void doAddRepeatedSfixed32(Integer repeatedSfixed32);

        protected abstract void doAddAllRepeatedSfixed32(List<Integer> repeatedSfixed32);

        protected abstract void doSetRepeatedSfixed32(List<Integer> repeatedSfixed32);

        protected abstract void doClearRepeatedSfixed32();

        protected abstract void doAddRepeatedSfixed64(Long repeatedSfixed64);

        protected abstract void doAddAllRepeatedSfixed64(List<Long> repeatedSfixed64);

        protected abstract void doSetRepeatedSfixed64(List<Long> repeatedSfixed64);

        protected abstract void doClearRepeatedSfixed64();

        protected abstract void doAddRepeatedFloat(Float repeatedFloat);

        protected abstract void doAddAllRepeatedFloat(List<Float> repeatedFloat);

        protected abstract void doSetRepeatedFloat(List<Float> repeatedFloat);

        protected abstract void doClearRepeatedFloat();

        protected abstract void doAddRepeatedDouble(Double repeatedDouble);

        protected abstract void doAddAllRepeatedDouble(List<Double> repeatedDouble);

        protected abstract void doSetRepeatedDouble(List<Double> repeatedDouble);

        protected abstract void doClearRepeatedDouble();

        protected abstract void doAddRepeatedBool(Boolean repeatedBool);

        protected abstract void doAddAllRepeatedBool(List<Boolean> repeatedBool);

        protected abstract void doSetRepeatedBool(List<Boolean> repeatedBool);

        protected abstract void doClearRepeatedBool();

        protected abstract void doAddRepeatedString(String repeatedString);

        protected abstract void doAddAllRepeatedString(List<String> repeatedString);

        protected abstract void doSetRepeatedString(List<String> repeatedString);

        protected abstract void doClearRepeatedString();

        protected abstract void doAddRepeatedBytes(byte[] repeatedBytes);

        protected abstract void doAddAllRepeatedBytes(List<byte[]> repeatedBytes);

        protected abstract void doSetRepeatedBytes(List<byte[]> repeatedBytes);

        protected abstract void doClearRepeatedBytes();

        protected abstract void doAddRepeatedMessage(NestedMessage repeatedMessage);

        protected abstract void doAddAllRepeatedMessage(List<NestedMessage> repeatedMessage);

        protected abstract void doSetRepeatedMessage(List<NestedMessage> repeatedMessage);

        protected abstract void doClearRepeatedMessage();

        protected abstract void doAddRepeatedEnum(TestEnum repeatedEnum);

        protected abstract void doAddAllRepeatedEnum(List<TestEnum> repeatedEnum);

        protected abstract void doSetRepeatedEnum(List<TestEnum> repeatedEnum);

        protected abstract void doClearRepeatedEnum();

        protected abstract void doPutStringToInt32(String key, int value);

        protected abstract void doPutAllStringToInt32(Map<String, Integer> values);

        protected abstract void doRemoveStringToInt32(String key);

        protected abstract void doClearStringToInt32();

        protected abstract Map<String, Integer> doGetStringToInt32Map();

        protected abstract void doPutInt32ToString(int key, String value);

        protected abstract void doPutAllInt32ToString(Map<Integer, String> values);

        protected abstract void doRemoveInt32ToString(int key);

        protected abstract void doClearInt32ToString();

        protected abstract Map<Integer, String> doGetInt32ToStringMap();

        protected abstract void doPutStringToMessage(String key, NestedMessage value);

        protected abstract void doPutAllStringToMessage(Map<String, NestedMessage> values);

        protected abstract void doRemoveStringToMessage(String key);

        protected abstract void doClearStringToMessage();

        protected abstract Map<String, NestedMessage> doGetStringToMessageMap();

        protected abstract void doPutStringToEnum(String key, TestEnum value);

        protected abstract void doPutAllStringToEnum(Map<String, TestEnum> values);

        protected abstract void doRemoveStringToEnum(String key);

        protected abstract void doClearStringToEnum();

        protected abstract Map<String, TestEnum> doGetStringToEnumMap();

        protected abstract void doPutInt64ToString(long key, String value);

        protected abstract void doPutAllInt64ToString(Map<Long, String> values);

        protected abstract void doRemoveInt64ToString(long key);

        protected abstract void doClearInt64ToString();

        protected abstract Map<Long, String> doGetInt64ToStringMap();

        protected abstract AllFieldTypes doBuild();

        protected abstract String getVersionId();

        @Override
        public final AllFieldTypes.Builder setRequiredInt32(int requiredInt32) {
            doSetRequiredInt32(requiredInt32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredInt32() {
            doClearRequiredInt32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredInt64(long requiredInt64) {
            doSetRequiredInt64(requiredInt64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredInt64() {
            doClearRequiredInt64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredUint32(int requiredUint32) {
            doSetRequiredUint32(requiredUint32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredUint32() {
            doClearRequiredUint32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredUint64(long requiredUint64) {
            doSetRequiredUint64(requiredUint64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredUint64() {
            doClearRequiredUint64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredSint32(int requiredSint32) {
            doSetRequiredSint32(requiredSint32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredSint32() {
            doClearRequiredSint32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredSint64(long requiredSint64) {
            doSetRequiredSint64(requiredSint64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredSint64() {
            doClearRequiredSint64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredFixed32(int requiredFixed32) {
            doSetRequiredFixed32(requiredFixed32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredFixed32() {
            doClearRequiredFixed32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredFixed64(long requiredFixed64) {
            doSetRequiredFixed64(requiredFixed64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredFixed64() {
            doClearRequiredFixed64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredSfixed32(int requiredSfixed32) {
            doSetRequiredSfixed32(requiredSfixed32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredSfixed32() {
            doClearRequiredSfixed32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredSfixed64(long requiredSfixed64) {
            doSetRequiredSfixed64(requiredSfixed64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredSfixed64() {
            doClearRequiredSfixed64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredFloat(float requiredFloat) {
            doSetRequiredFloat(requiredFloat);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredFloat() {
            doClearRequiredFloat();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredDouble(double requiredDouble) {
            doSetRequiredDouble(requiredDouble);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredDouble() {
            doClearRequiredDouble();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredBool(boolean requiredBool) {
            doSetRequiredBool(requiredBool);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredBool() {
            doClearRequiredBool();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredString(String requiredString) {
            doSetRequiredString(requiredString);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredString() {
            doClearRequiredString();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredBytes(byte[] requiredBytes) {
            doSetRequiredBytes(requiredBytes);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredBytes() {
            doClearRequiredBytes();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredMessage(NestedMessage requiredMessage) {
            doSetRequiredMessage(requiredMessage);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredMessage() {
            doClearRequiredMessage();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRequiredEnum(TestEnum requiredEnum) {
            doSetRequiredEnum(requiredEnum);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRequiredEnum() {
            doClearRequiredEnum();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalInt32(Integer optionalInt32) {
            doSetOptionalInt32(optionalInt32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalInt32() {
            doClearOptionalInt32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalInt64(Long optionalInt64) {
            doSetOptionalInt64(optionalInt64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalInt64() {
            doClearOptionalInt64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalUint32(Integer optionalUint32) {
            doSetOptionalUint32(optionalUint32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalUint32() {
            doClearOptionalUint32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalUint64(Long optionalUint64) {
            doSetOptionalUint64(optionalUint64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalUint64() {
            doClearOptionalUint64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalSint32(Integer optionalSint32) {
            doSetOptionalSint32(optionalSint32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalSint32() {
            doClearOptionalSint32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalSint64(Long optionalSint64) {
            doSetOptionalSint64(optionalSint64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalSint64() {
            doClearOptionalSint64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalFixed32(Integer optionalFixed32) {
            doSetOptionalFixed32(optionalFixed32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalFixed32() {
            doClearOptionalFixed32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalFixed64(Long optionalFixed64) {
            doSetOptionalFixed64(optionalFixed64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalFixed64() {
            doClearOptionalFixed64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalSfixed32(Integer optionalSfixed32) {
            doSetOptionalSfixed32(optionalSfixed32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalSfixed32() {
            doClearOptionalSfixed32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalSfixed64(Long optionalSfixed64) {
            doSetOptionalSfixed64(optionalSfixed64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalSfixed64() {
            doClearOptionalSfixed64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalFloat(Float optionalFloat) {
            doSetOptionalFloat(optionalFloat);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalFloat() {
            doClearOptionalFloat();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalDouble(Double optionalDouble) {
            doSetOptionalDouble(optionalDouble);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalDouble() {
            doClearOptionalDouble();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalBool(Boolean optionalBool) {
            doSetOptionalBool(optionalBool);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalBool() {
            doClearOptionalBool();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalString(String optionalString) {
            doSetOptionalString(optionalString);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalString() {
            doClearOptionalString();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalBytes(byte[] optionalBytes) {
            doSetOptionalBytes(optionalBytes);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalBytes() {
            doClearOptionalBytes();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalMessage(NestedMessage optionalMessage) {
            doSetOptionalMessage(optionalMessage);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalMessage() {
            doClearOptionalMessage();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setOptionalEnum(TestEnum optionalEnum) {
            doSetOptionalEnum(optionalEnum);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearOptionalEnum() {
            doClearOptionalEnum();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedInt32(Integer repeatedInt32) {
            doAddRepeatedInt32(repeatedInt32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedInt32(List<Integer> repeatedInt32) {
            doAddAllRepeatedInt32(repeatedInt32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedInt32(List<Integer> repeatedInt32) {
            doSetRepeatedInt32(repeatedInt32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedInt32() {
            doClearRepeatedInt32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedInt64(Long repeatedInt64) {
            doAddRepeatedInt64(repeatedInt64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedInt64(List<Long> repeatedInt64) {
            doAddAllRepeatedInt64(repeatedInt64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedInt64(List<Long> repeatedInt64) {
            doSetRepeatedInt64(repeatedInt64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedInt64() {
            doClearRepeatedInt64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedUint32(Integer repeatedUint32) {
            doAddRepeatedUint32(repeatedUint32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedUint32(List<Integer> repeatedUint32) {
            doAddAllRepeatedUint32(repeatedUint32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedUint32(List<Integer> repeatedUint32) {
            doSetRepeatedUint32(repeatedUint32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedUint32() {
            doClearRepeatedUint32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedUint64(Long repeatedUint64) {
            doAddRepeatedUint64(repeatedUint64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedUint64(List<Long> repeatedUint64) {
            doAddAllRepeatedUint64(repeatedUint64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedUint64(List<Long> repeatedUint64) {
            doSetRepeatedUint64(repeatedUint64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedUint64() {
            doClearRepeatedUint64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedSint32(Integer repeatedSint32) {
            doAddRepeatedSint32(repeatedSint32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedSint32(List<Integer> repeatedSint32) {
            doAddAllRepeatedSint32(repeatedSint32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedSint32(List<Integer> repeatedSint32) {
            doSetRepeatedSint32(repeatedSint32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedSint32() {
            doClearRepeatedSint32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedSint64(Long repeatedSint64) {
            doAddRepeatedSint64(repeatedSint64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedSint64(List<Long> repeatedSint64) {
            doAddAllRepeatedSint64(repeatedSint64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedSint64(List<Long> repeatedSint64) {
            doSetRepeatedSint64(repeatedSint64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedSint64() {
            doClearRepeatedSint64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedFixed32(Integer repeatedFixed32) {
            doAddRepeatedFixed32(repeatedFixed32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedFixed32(List<Integer> repeatedFixed32) {
            doAddAllRepeatedFixed32(repeatedFixed32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedFixed32(List<Integer> repeatedFixed32) {
            doSetRepeatedFixed32(repeatedFixed32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedFixed32() {
            doClearRepeatedFixed32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedFixed64(Long repeatedFixed64) {
            doAddRepeatedFixed64(repeatedFixed64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedFixed64(List<Long> repeatedFixed64) {
            doAddAllRepeatedFixed64(repeatedFixed64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedFixed64(List<Long> repeatedFixed64) {
            doSetRepeatedFixed64(repeatedFixed64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedFixed64() {
            doClearRepeatedFixed64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedSfixed32(Integer repeatedSfixed32) {
            doAddRepeatedSfixed32(repeatedSfixed32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedSfixed32(List<Integer> repeatedSfixed32) {
            doAddAllRepeatedSfixed32(repeatedSfixed32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedSfixed32(List<Integer> repeatedSfixed32) {
            doSetRepeatedSfixed32(repeatedSfixed32);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedSfixed32() {
            doClearRepeatedSfixed32();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedSfixed64(Long repeatedSfixed64) {
            doAddRepeatedSfixed64(repeatedSfixed64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedSfixed64(List<Long> repeatedSfixed64) {
            doAddAllRepeatedSfixed64(repeatedSfixed64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedSfixed64(List<Long> repeatedSfixed64) {
            doSetRepeatedSfixed64(repeatedSfixed64);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedSfixed64() {
            doClearRepeatedSfixed64();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedFloat(Float repeatedFloat) {
            doAddRepeatedFloat(repeatedFloat);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedFloat(List<Float> repeatedFloat) {
            doAddAllRepeatedFloat(repeatedFloat);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedFloat(List<Float> repeatedFloat) {
            doSetRepeatedFloat(repeatedFloat);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedFloat() {
            doClearRepeatedFloat();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedDouble(Double repeatedDouble) {
            doAddRepeatedDouble(repeatedDouble);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedDouble(List<Double> repeatedDouble) {
            doAddAllRepeatedDouble(repeatedDouble);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedDouble(List<Double> repeatedDouble) {
            doSetRepeatedDouble(repeatedDouble);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedDouble() {
            doClearRepeatedDouble();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedBool(Boolean repeatedBool) {
            doAddRepeatedBool(repeatedBool);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedBool(List<Boolean> repeatedBool) {
            doAddAllRepeatedBool(repeatedBool);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedBool(List<Boolean> repeatedBool) {
            doSetRepeatedBool(repeatedBool);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedBool() {
            doClearRepeatedBool();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedString(String repeatedString) {
            doAddRepeatedString(repeatedString);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedString(List<String> repeatedString) {
            doAddAllRepeatedString(repeatedString);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedString(List<String> repeatedString) {
            doSetRepeatedString(repeatedString);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedString() {
            doClearRepeatedString();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedBytes(byte[] repeatedBytes) {
            doAddRepeatedBytes(repeatedBytes);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedBytes(List<byte[]> repeatedBytes) {
            doAddAllRepeatedBytes(repeatedBytes);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedBytes(List<byte[]> repeatedBytes) {
            doSetRepeatedBytes(repeatedBytes);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedBytes() {
            doClearRepeatedBytes();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedMessage(NestedMessage repeatedMessage) {
            doAddRepeatedMessage(repeatedMessage);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedMessage(
                List<NestedMessage> repeatedMessage) {
            doAddAllRepeatedMessage(repeatedMessage);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedMessage(List<NestedMessage> repeatedMessage) {
            doSetRepeatedMessage(repeatedMessage);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedMessage() {
            doClearRepeatedMessage();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addRepeatedEnum(TestEnum repeatedEnum) {
            doAddRepeatedEnum(repeatedEnum);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder addAllRepeatedEnum(List<TestEnum> repeatedEnum) {
            doAddAllRepeatedEnum(repeatedEnum);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder setRepeatedEnum(List<TestEnum> repeatedEnum) {
            doSetRepeatedEnum(repeatedEnum);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearRepeatedEnum() {
            doClearRepeatedEnum();
            return this;
        }

        @Override
        public final AllFieldTypes.Builder putStringToInt32(String key, int value) {
            doPutStringToInt32(key, value);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder putAllStringToInt32(Map<String, Integer> values) {
            doPutAllStringToInt32(values);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder removeStringToInt32(String key) {
            doRemoveStringToInt32(key);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearStringToInt32() {
            doClearStringToInt32();
            return this;
        }

        @Override
        public final Map<String, Integer> getStringToInt32Map() {
            return Collections.unmodifiableMap(doGetStringToInt32Map());
        }

        @Override
        public final AllFieldTypes.Builder putInt32ToString(int key, String value) {
            doPutInt32ToString(key, value);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder putAllInt32ToString(Map<Integer, String> values) {
            doPutAllInt32ToString(values);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder removeInt32ToString(int key) {
            doRemoveInt32ToString(key);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearInt32ToString() {
            doClearInt32ToString();
            return this;
        }

        @Override
        public final Map<Integer, String> getInt32ToStringMap() {
            return Collections.unmodifiableMap(doGetInt32ToStringMap());
        }

        @Override
        public final AllFieldTypes.Builder putStringToMessage(String key, NestedMessage value) {
            doPutStringToMessage(key, value);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder putAllStringToMessage(
                Map<String, NestedMessage> values) {
            doPutAllStringToMessage(values);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder removeStringToMessage(String key) {
            doRemoveStringToMessage(key);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearStringToMessage() {
            doClearStringToMessage();
            return this;
        }

        @Override
        public final Map<String, NestedMessage> getStringToMessageMap() {
            return Collections.unmodifiableMap(doGetStringToMessageMap());
        }

        @Override
        public final AllFieldTypes.Builder putStringToEnum(String key, TestEnum value) {
            doPutStringToEnum(key, value);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder putAllStringToEnum(Map<String, TestEnum> values) {
            doPutAllStringToEnum(values);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder removeStringToEnum(String key) {
            doRemoveStringToEnum(key);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearStringToEnum() {
            doClearStringToEnum();
            return this;
        }

        @Override
        public final Map<String, TestEnum> getStringToEnumMap() {
            return Collections.unmodifiableMap(doGetStringToEnumMap());
        }

        @Override
        public final AllFieldTypes.Builder putInt64ToString(long key, String value) {
            doPutInt64ToString(key, value);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder putAllInt64ToString(Map<Long, String> values) {
            doPutAllInt64ToString(values);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder removeInt64ToString(long key) {
            doRemoveInt64ToString(key);
            return this;
        }

        @Override
        public final AllFieldTypes.Builder clearInt64ToString() {
            doClearInt64ToString();
            return this;
        }

        @Override
        public final Map<Long, String> getInt64ToStringMap() {
            return Collections.unmodifiableMap(doGetInt64ToStringMap());
        }

        @Override
        public final AllFieldTypes build() {
            return doBuild();
        }
    }
}
